export interface Env {
  DB: D1Database;
  R2: R2Bucket;
  JWT_SECRET?: string;
  JWT_REFRESH_SECRET?: string;
  BREVO_API_KEY?: string;
  BREVO_FROM_EMAIL?: string;
  FRONTEND_ORIGIN?: string;
}

type Row = Record<string, unknown>;
type User = { id: string; username: string; email: string; avatar_url?: string | null; bio?: string | null; status?: string | null };
const TABLES = new Set(['users','user_sessions','password_reset_tokens','security_events','user_settings','notification_preferences','follows','blocks','mutes','posts','post_media','post_likes','saved_posts','comments','comment_likes','mentions','notifications','reward_offers','offerwall_events','reward_transactions','wallets','wallet_transactions','payment_providers','payment_transactions','withdrawals','withdrawal_attempts','admin_users','reports','moderation_actions','conversations','conversation_participants','messages']);
const enc = new TextEncoder();
const now = () => Math.floor(Date.now()/1000);
const newId = () => crypto.randomUUID();
const text = (v:unknown) => typeof v === 'string' ? v : v == null ? '' : String(v);
const ident = (v:string) => { if(!/^[A-Za-z_][A-Za-z0-9_]*$/.test(v)) throw new Error('unsafe identifier'); return `"${v}"`; };
const first = (s:Set<string>, names:string[]) => names.find(n=>s.has(n));
function json(data:unknown,status=200,headers:HeadersInit={}):Response{return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...headers}});}
function cors(env:Env,req:Request):HeadersInit{const h=new Headers(),origin=req.headers.get('Origin');if(origin&&env.FRONTEND_ORIGIN&&origin===env.FRONTEND_ORIGIN){h.set('access-control-allow-origin',origin);h.set('vary','Origin');h.set('access-control-allow-credentials','true');}h.set('access-control-allow-methods','GET,POST,PATCH,DELETE,OPTIONS');h.set('access-control-allow-headers','content-type');return h;}
async function columns(db:D1Database,name:string){if(!TABLES.has(name))throw new Error('unknown table');const r=await db.prepare(`PRAGMA table_info(${ident(name)})`).all<Row>();return new Set((r.results||[]).map(x=>text(x.name)));}
async function insert(db:D1Database,name:string,values:Record<string,unknown>){const c=await columns(db,name),e=Object.entries(values).filter(([k,v])=>c.has(k)&&v!==undefined);if(!e.length)throw new Error(`No compatible columns for ${name}`);return db.prepare(`INSERT INTO ${ident(name)} (${e.map(([k])=>ident(k)).join(',')}) VALUES (${e.map(()=>'?').join(',')})`).bind(...e.map(([,v])=>v)).run();}
async function update(db:D1Database,name:string,where:string,args:unknown[],values:Record<string,unknown>){const c=await columns(db,name),e=Object.entries(values).filter(([k,v])=>c.has(k)&&v!==undefined);if(!e.length)throw new Error(`No compatible columns for ${name}`);return db.prepare(`UPDATE ${ident(name)} SET ${e.map(([k])=>`${ident(k)}=?`).join(',')} WHERE ${where}`).bind(...e.map(([,v])=>v),...args).run();}
function cookie(name:string,value:string,maxAge:number){return `${name}=${value}; Path=/; Max-Age=${maxAge}; HttpOnly; Secure; SameSite=Lax`;}
function clearCookie(name:string){return `${name}=; Path=/; Max-Age=0; HttpOnly; Secure; SameSite=Lax`;}
function parseCookies(req:Request){return Object.fromEntries((req.headers.get('cookie')||'').split(';').map(x=>x.trim()).filter(Boolean).map(x=>{const i=x.indexOf('=');return [x.slice(0,i),x.slice(i+1)]}));}
function b64(bytes:ArrayBuffer|Uint8Array){const view=bytes instanceof Uint8Array?bytes:new Uint8Array(bytes);return btoa(String.fromCharCode(...view)).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');}
function unb64(s:string){const p=s.replaceAll('-','+').replaceAll('_','/'),pad='='.repeat((4-p.length%4)%4);return Uint8Array.from(atob(p+pad),c=>c.charCodeAt(0));}
async function sha(v:string){return b64(await crypto.subtle.digest('SHA-256',enc.encode(v)));}
async function hmac(secret:string,v:string){const k=await crypto.subtle.importKey('raw',enc.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return b64(await crypto.subtle.sign('HMAC',k,enc.encode(v)));}
async function signJwt(secret:string,p:Record<string,unknown>){const h=b64(enc.encode(JSON.stringify({alg:'HS256',typ:'JWT'}))),b=b64(enc.encode(JSON.stringify(p)));return `${h}.${b}.${await hmac(secret,`${h}.${b}`)}`;}
async function verifyJwt(secret:string,t:string){try{const [h,p,s]=t.split('.');if(!h||!p||!s||await hmac(secret,`${h}.${p}`)!==s)return null;const v=JSON.parse(new TextDecoder().decode(unb64(p)));return typeof v.exp==='number'&&v.exp<=now()?null:v;}catch{return null;}}
function randomToken(n=32){const a=new Uint8Array(n);crypto.getRandomValues(a);return [...a].map(x=>x.toString(16).padStart(2,'0')).join('');}
async function passwordHash(password:string,salt=randomToken(16)){const k=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt:enc.encode(salt),iterations:210000,hash:'SHA-256'},k,256);return `210000$${salt}$${b64(bits)}`;}
async function passwordOk(password:string,stored:string){const p=stored.split('$');return p.length===3&&(await passwordHash(password,p[1]))===stored;}
const rowId=(r:Row)=>text(r.id??r.user_id);const rowPassword=(r:Row)=>text(r.password_hash??r.password_digest??r.password??'');
async function getUser(db:D1Database,id:string):Promise<User|null>{const c=await columns(db,'users'),ic=first(c,['id','user_id']),un=first(c,['username','handle','name']),em=first(c,['email','email_address']),av=first(c,['avatar_url','avatar','profile_image_url']),bio=first(c,['bio','about']),st=first(c,['status','account_status']);if(!ic)throw new Error('users id missing');const s=[`${ident(ic)} AS id`,un?`${ident(un)} AS username`:"'' AS username",em?`${ident(em)} AS email`:"'' AS email"];if(av)s.push(`${ident(av)} AS avatar_url`);if(bio)s.push(`${ident(bio)} AS bio`);if(st)s.push(`${ident(st)} AS status`);return await db.prepare(`SELECT ${s.join(',')} FROM users WHERE ${ident(ic)}=? LIMIT 1`).bind(id).first<User>();}
async function findUser(db:D1Database,v:string){const c=await columns(db,'users'),ic=first(c,['id','user_id']),em=first(c,['email','email_address']),un=first(c,['username','handle']);if(em&&un)return db.prepare(`SELECT * FROM users WHERE lower(${ident(em)})=lower(?) OR lower(${ident(un)})=lower(?) LIMIT 1`).bind(v,v).first<Row>();if(em)return db.prepare(`SELECT * FROM users WHERE lower(${ident(em)})=lower(?) LIMIT 1`).bind(v).first<Row>();if(un)return db.prepare(`SELECT * FROM users WHERE lower(${ident(un)})=lower(?) LIMIT 1`).bind(v).first<Row>();if(ic)return db.prepare(`SELECT * FROM users WHERE ${ident(ic)}=? LIMIT 1`).bind(v).first<Row>();return null;}
async function createTokens(env:Env,userId:string){if(!env.JWT_SECRET||!env.JWT_REFRESH_SECRET)throw new Error('Authentication configuration unavailable');const sid=newId(),rawRefresh=randomToken(32),hash=await sha(rawRefresh),aexp=now()+900,rexp=now()+2592000;await insert(env.DB,'user_sessions',{id:sid,user_id:userId,refresh_token_hash:hash,token_hash:hash,session_token_hash:hash,created_at:now(),expires_at:rexp,revoked_at:null});const access=await signJwt(env.JWT_SECRET,{sub:userId,sid,typ:'access',exp:aexp}),refresh=await signJwt(env.JWT_REFRESH_SECRET,{sub:userId,sid,typ:'refresh',jti:rawRefresh,exp:rexp});return {access,refresh,aexp,rexp,sid};}
async function revokeSession(env:Env,sid:string){const c=await columns(env.DB,'user_sessions'),ic=first(c,['id','session_id']),rc=first(c,['revoked_at','invalidated_at']);if(ic&&rc)await update(env.DB,'user_sessions',`${ident(ic)}=?`,[sid],{[rc]:now()});}
async function auth(env:Env,req:Request){if(!env.JWT_SECRET||!env.JWT_REFRESH_SECRET)return null;const c=parseCookies(req),access=c.sphere_access?await verifyJwt(env.JWT_SECRET,c.sphere_access):null;if(access?.typ==='access'&&access.sub){const user=await getUser(env.DB,text(access.sub));if(user&&!(user.status&&['banned','disabled','suspended'].includes(user.status.toLowerCase())))return {user,sid:text(access.sid),rotated:false};}const r=c.sphere_refresh?await verifyJwt(env.JWT_REFRESH_SECRET,c.sphere_refresh):null;if(r?.typ!=='refresh'||!r.sub||!r.sid||!r.jti)return null;const h=await sha(text(r.jti)),cols=await columns(env.DB,'user_sessions'),ic=first(cols,['id','session_id']),hc=first(cols,['refresh_token_hash','token_hash','session_token_hash']);if(!ic||!hc)return null;const live=await env.DB.prepare(`SELECT 1 FROM user_sessions WHERE ${ident(ic)}=? AND ${ident(hc)}=? AND (revoked_at IS NULL OR revoked_at=0) LIMIT 1`).bind(text(r.sid),h).first();if(!live)return null;const user=await getUser(env.DB,text(r.sub));if(!user)return null;await revokeSession(env,text(r.sid));const tokens=await createTokens(env,text(r.sub));return {user,sid:tokens.sid,rotated:true,tokens};}
function requireAuth(a:Awaited<ReturnType<typeof auth>>):asserts a{if(!a)throw Object.assign(new Error('Authentication required'),{status:401});}
function setTokens(h:Headers,t:any){h.append('set-cookie',cookie('sphere_access',t.access,Math.max(1,t.aexp-now())));h.append('set-cookie',cookie('sphere_refresh',t.refresh,Math.max(1,t.reexp-now())));}
function clearTokens(h:Headers){h.append('set-cookie',clearCookie('sphere_access'));h.append('set-cookie',clearCookie('sphere_refresh'));}
async function notify(db:D1Database,recipient:string,actor:string,type:string,entity?:string){try{await insert(db,'notifications',{id:newId(),user_id:recipient,recipient_id:recipient,actor_id:actor,type,entity_id:entity,reference_id:entity,created_at:now(),read_at:null,is_read:0});}catch{}}
async function sendBrevo(env:Env,email:string,token:string){if(!env.BREVO_API_KEY||!env.BREVO_FROM_EMAIL||!env.FRONTEND_ORIGIN)return false;const r=await fetch('https://api.brevo.com/v3/smtp/email',{method:'POST',headers:{'content-type':'application/json','api-key':env.BREVO_API_KEY},body:JSON.stringify({sender:{email:env.BREVO_FROM_EMAIL},to:[{email}],subject:'Reset your Sphere password',htmlContent:`<p>Reset your Sphere password.</p><p><a href="${env.FRONTEND_ORIGIN}/reset-password?token=${encodeURIComponent(token)}">Reset password</a></p>`})});return r.ok;}
async function handle(env:Env,req:Request){const url=new URL(req.url),path=url.pathname.replace(/\/+$/,'')||'/';if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(env,req)});const ch=cors(env,req),body=async()=>req.headers.get('content-type')?.includes('application/json')?await req.json<Record<string,unknown>>():{};if(path==='/health')return json({ok:true,service:'sphere-api',database:'D1',storage:'R2'},200,ch);let a=await auth(env,req);
if(path==='/auth/signup'&&req.method==='POST'){const b=await body(),username=text(b.username).trim().toLowerCase(),email=text(b.email).trim().toLowerCase(),password=text(b.password);if(!/^[a-z0-9_.]{3,30}$/.test(username)||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||password.length<8)return json({error:'Invalid signup details'},400,ch);if(await findUser(env.DB,username)||await findUser(env.DB,email))return json({error:'Unable to create account with those details'},409,ch);const ph=await passwordHash(password),id=newId();await insert(env.DB,'users',{id,user_id:id,username,email,password_hash:ph,password_digest:ph,created_at:now(),updated_at:now(),status:'active'});const t=await createTokens(env,id),h=new Headers(ch);setTokens(h,t);return json({user:await getUser(env.DB,id)},201,h);}
if(path==='/auth/login'&&req.method==='POST'){const b=await body(),v=text(b.email||b.username).trim().toLowerCase(),password=text(b.password),r=await findUser(env.DB,v);if(!r||!(await passwordOk(password,rowPassword(r))))return json({error:'Invalid email/username or password'},401,ch);const t=await createTokens(env,rowId(r)),h=new Headers(ch);setTokens(h,t);return json({user:await getUser(env.DB,rowId(r))},200,h);}
if(path==='/auth/session'&&req.method==='GET'){if(!a)return json({user:null},200,ch);if(a.rotated&&a.tokens){const h=new Headers(ch);setTokens(h,a.tokens);return json({user:a.user},200,h);}return json({user:a.user},200,ch);}
if(path==='/auth/refresh'&&req.method==='POST'){if(!a?.rotated||!a.tokens)return json({error:'Refresh required'},401,ch);const h=new Headers(ch);setTokens(h,a.tokens);return json({user:a.user},200,h);}
if(path==='/auth/logout'&&req.method==='POST'){if(a)await revokeSession(env,a.sid);const h=new Headers(ch);clearTokens(h);return json({ok:true},200,h);}
if(path==='/auth/forgot-password'&&req.method==='POST'){const b=await body(),email=text(b.email).trim().toLowerCase(),r=await findUser(env.DB,email);if(r){const token=randomToken(32);const hash=await sha(token);await insert(env.DB,'password_reset_tokens',{id:newId(),user_id:rowId(r),token_hash:hash,token_digest:hash,expires_at:now()+3600,created_at:now(),used_at:null});await sendBrevo(env,email,token);}return json({ok:true,message:'If that account exists, a reset email has been sent.'},200,ch);}
if(path==='/auth/reset-password'&&req.method==='POST'){const b=await body(),token=text(b.token),password=text(b.password);if(token.length<20||password.length<8)return json({error:'Invalid reset request'},400,ch);const c=await columns(env.DB,'password_reset_tokens'),tc=first(c,['token_hash','token_digest','token']),uc=first(c,['user_id']),ec=first(c,['expires_at','expires']),used=first(c,['used_at','used']);if(!tc||!uc)return json({error:'Reset unavailable'},503,ch);const hash=await sha(token),conds=[`${ident(tc)}=?`],args:unknown[]=[hash];if(ec){conds.push(`${ident(ec)}> ?`);args.push(now());}if(used)conds.push(`(${ident(used)} IS NULL OR ${ident(used)}=0)`);const r=await env.DB.prepare(`SELECT ${ident(uc)} AS user_id FROM password_reset_tokens WHERE ${conds.join(' AND ')} LIMIT 1`).bind(...args).first<Row>();if(!r)return json({error:'Invalid or expired reset token'},400,ch);const ph=await passwordHash(password),ucols=await columns(env.DB,'users'),ic=first(ucols,['id','user_id']);if(!ic)return json({error:'Reset unavailable'},503,ch);await update(env.DB,'users',`${ident(ic)}=?`,[text(r.user_id)],{password_hash:ph,password_digest:ph,updated_at:now()});if(used)await update(env.DB,'password_reset_tokens',`${ident(tc)}=?`,[hash],{[used]:now()});return json({ok:true},200,ch);}
if(path==='/me'&&req.method==='GET'){requireAuth(a);return json({user:a.user},200,ch);}if(path==='/me'&&req.method==='PATCH'){requireAuth(a);const b=await body(),username=text(b.username).trim().toLowerCase(),bio=text(b.bio).slice(0,500),avatar=text(b.avatar_url);if(username&&!/^[a-z0-9_.]{3,30}$/.test(username))return json({error:'Invalid username'},400,ch);if(username&&username!==a.user.username){const r=await findUser(env.DB,username);if(r&&rowId(r)!==a.user.id)return json({error:'Username already in use'},409,ch);}const c=await columns(env.DB,'users'),ic=first(c,['id','user_id']);if(!ic)return json({error:'Profile unavailable'},503,ch);await update(env.DB,'users',`${ident(ic)}=?`,[a.user.id],{username:username||undefined,bio,avatar_url:avatar||undefined,updated_at:now()});return json({user:await getUser(env.DB,a.user.id)},200,ch);}
if(path==='/upload/image'&&req.method==='POST'){requireAuth(a);const form=await req.formData(),file=form.get('file');if(!(file instanceof File))return json({error:'Image file required'},400,ch);if(file.size>10*1024*1024)return json({error:'Image exceeds 10 MB'},413,ch);const types:{[k:string]:string}={'image/jpeg':'jpg','image/png':'png','image/webp':'webp','image/gif':'gif'},ext=types[file.type.toLowerCase()];if(!ext)return json({error:'Only JPEG, PNG, WebP and GIF images are supported'},415,ch);const key=`users/${a.user.id}/images/${newId()}.${ext}`;await env.R2.put(key,file.stream(),{httpMetadata:{contentType:file.type.toLowerCase(),cacheControl:'public, max-age=31536000, immutable'},customMetadata:{owner_id:a.user.id}});return json({key},201,ch);}
if(path.startsWith('/media/')&&req.method==='GET'){const key=decodeURIComponent(path.slice(7));if(!/^users\/[^/]+\/images\/[A-Za-z0-9-]+\.(jpg|png|webp|gif)$/.test(key))return new Response('Not found',{status:404});const obj=await env.R2.get(key);if(!obj)return new Response('Not found',{status:404});return new Response(obj.body,{headers:{'content-type':obj.httpMetadata?.contentType||'application/octet-stream','cache-control':'public, max-age=31536000, immutable'}});}
if(path==='/posts'&&req.method==='GET'){requireAuth(a);const limit=Math.min(Math.max(Number(url.searchParams.get('limit')||20),1),50),offset=Math.max(Number(url.searchParams.get('offset')||0),0),rows=await env.DB.prepare('SELECT * FROM posts ORDER BY created_at DESC LIMIT ? OFFSET ?').bind(limit,offset).all<Row>();const posts=[];for(const r of rows.results||[]){const pid=rowId(r);let media=null;try{const m=await columns(env.DB,'post_media'),pc=first(m,['post_id']);if(pc)media=await env.DB.prepare(`SELECT * FROM post_media WHERE ${ident(pc)}=? LIMIT 1`).bind(pid).first<Row>();}catch{}const ac=first(await columns(env.DB,'posts'),['user_id','author_id','creator_id']);const author=ac?await getUser(env.DB,text(r[ac])):null;let like_count=0;try{const l=await columns(env.DB,'post_likes'),pc=first(l,['post_id']);if(pc){const n=await env.DB.prepare(`SELECT COUNT(*) AS n FROM post_likes WHERE ${ident(pc)}=?`).bind(pid).first<Row>();like_count=Number(n?.n||0);}}catch{}posts.push({...r,id:pid,author,media,like_count});}return json({posts},200,ch);}
if(path==='/posts'&&req.method==='POST'){requireAuth(a);const b=await body(),caption=text(b.caption).slice(0,2200),key=text(b.imageKey),music=typeof b.music==='object'&&b.music?JSON.stringify(b.music):undefined;if(!key||!key.startsWith(`users/${a.user.id}/images/`))return json({error:'Owned image is required'},400,ch);const obj=await env.R2.head(key);if(!obj)return json({error:'Image was not found'},400,ch);const pid=newId();await insert(env.DB,'posts',{id:pid,post_id:pid,user_id:a.user.id,author_id:a.user.id,caption,music,music_metadata:music,created_at:now(),updated_at:now(),status:'published'});try{await insert(env.DB,'post_media',{id:newId(),post_id:pid,object_key:key,r2_key:key,storage_key:key,mime_type:obj.httpMetadata?.contentType,content_type:obj.httpMetadata?.contentType,size_bytes:obj.size,created_at:now()});}catch{await env.DB.prepare('DELETE FROM posts WHERE id=? OR post_id=?').bind(pid,pid).run();return json({error:'Unable to persist post media'},500,ch);}return json({post_id:pid},201,ch);}
const act=path.match(/^\/posts\/([^/]+)\/(like|save)$/);if(act&&req.method==='POST'){requireAuth(a);const pid=decodeURIComponent(act[1]),type=act[2],table=type==='like'?'post_likes':'saved_posts',c=await columns(env.DB,table),pc=first(c,['post_id']),uc=first(c,['user_id','actor_id']);if(!pc||!uc)return json({error:'Unavailable'},503,ch);const ex=await env.DB.prepare(`SELECT 1 FROM ${ident(table)} WHERE ${ident(pc)}=? AND ${ident(uc)}=? LIMIT 1`).bind(pid,a.user.id).first();if(ex){await env.DB.prepare(`DELETE FROM ${ident(table)} WHERE ${ident(pc)}=? AND ${ident(uc)}=?`).bind(pid,a.user.id).run();return json({[type==='like'?'liked':'saved']:false},200,ch);}await insert(env.DB,table,{id:newId(),post_id:pid,user_id:a.user.id,actor_id:a.user.id,created_at:now()});return json({[type==='like'?'liked':'saved']:true},200,ch);}
if(path.startsWith('/posts/')&&path.endsWith('/comments')&&req.method==='POST'){requireAuth(a);const pid=decodeURIComponent(path.slice(7,-9)),b=await body(),content=text(b.content).trim().slice(0,2000),parent=text(b.parent_id)||undefined;if(!content)return json({error:'Comment is required'},400,ch);const c=await columns(env.DB,'comments'),pc=first(c,['post_id']),uc=first(c,['user_id','author_id']),cc=first(c,['content','body']);if(!pc||!uc||!cc)return json({error:'Comments unavailable'},503,ch);const cid=newId();await insert(env.DB,'comments',{id:cid,comment_id:cid,post_id:pid,user_id:a.user.id,author_id:a.user.id,content,body:content,parent_id:parent,reply_to_id:parent,created_at:now(),updated_at:now()});return json({comment_id:cid},201,ch);}
if(path==='/follows'&&req.method==='POST'){requireAuth(a);const b=await body(),target=text(b.user_id);if(!target||target===a.user.id)return json({error:'Invalid follow target'},400,ch);const c=await columns(env.DB,'follows'),fc=first(c,['follower_id','from_user_id','user_id']),tc=first(c,['following_id','to_user_id','target_user_id']);if(!fc||!tc)return json({error:'Follows unavailable'},503,ch);const ex=await env.DB.prepare(`SELECT 1 FROM follows WHERE ${ident(fc)}=? AND ${ident(tc)}=? LIMIT 1`).bind(a.user.id,target).first();if(ex){await env.DB.prepare(`DELETE FROM follows WHERE ${ident(fc)}=? AND ${ident(tc)}=?`).bind(a.user.id,target).run();return json({following:false},200,ch);}await insert(env.DB,'follows',{id:newId(),follower_id:a.user.id,from_user_id:a.user.id,user_id:a.user.id,following_id:target,to_user_id:target,target_user_id:target,created_at:now()});await notify(env.DB,target,a.user.id,'follow',a.user.id);return json({following:true},200,ch);}
if(path==='/notifications'&&req.method==='GET'){requireAuth(a);const c=await columns(env.DB,'notifications'),uc=first(c,['user_id','recipient_id']);if(!uc)return json({notifications:[]},200,ch);const r=await env.DB.prepare(`SELECT * FROM notifications WHERE ${ident(uc)}=? ORDER BY created_at DESC LIMIT 50`).bind(a.user.id).all<Row>();return json({notifications:r.results||[]},200,ch);}
if(path==='/search'&&req.method==='GET'){requireAuth(a);const q=text(url.searchParams.get('q')).trim();if(q.length<2)return json({users:[],posts:[]},200,ch);const us=await env.DB.prepare('SELECT id,username,email,bio,avatar_url FROM users WHERE lower(username) LIKE lower(?) LIMIT 20').bind(`%${q}%`).all<Row>().catch(()=>({results:[]}));const ps=await env.DB.prepare('SELECT * FROM posts WHERE lower(caption) LIKE lower(?) ORDER BY created_at DESC LIMIT 20').bind(`%${q}%`).all<Row>().catch(()=>({results:[]}));return json({users:us.results||[],posts:ps.results||[]},200,ch);}
if(path==='/settings'&&req.method==='GET'){requireAuth(a);try{const c=await columns(env.DB,'user_settings'),uc=first(c,['user_id']);const r=uc?await env.DB.prepare(`SELECT * FROM user_settings WHERE ${ident(uc)}=? LIMIT 1`).bind(a.user.id).first<Row>():null;return json({settings:r||{}},200,ch);}catch{return json({settings:{}},200,ch);}}
if(path==='/settings'&&req.method==='PATCH'){requireAuth(a);const b=await body();try{await insert(env.DB,'user_settings',{id:newId(),user_id:a.user.id,created_at:now()});}catch{}const c=await columns(env.DB,'user_settings'),uc=first(c,['user_id']);if(!uc)return json({error:'Settings unavailable'},503,ch);await update(env.DB,'user_settings',`${ident(uc)}=?`,[a.user.id],{allow_messages:typeof b.allow_messages==='boolean'?b.allow_messages:undefined,private_account:typeof b.private_account==='boolean'?b.private_account:undefined,updated_at:now()});return json({ok:true},200,ch);}
for(const kind of ['blocks','mutes'] as const){if(path===`/${kind}`&&req.method==='POST'){requireAuth(a);const b=await body(),target=text(b.user_id);if(!target||target===a.user.id)return json({error:'Invalid target'},400,ch);const c=await columns(env.DB,kind),uc=first(c,['blocker_id','muter_id','user_id','from_user_id']),tc=first(c,['blocked_id','muted_id','target_user_id','to_user_id']);if(!uc||!tc)return json({error:'Unavailable'},503,ch);const ex=await env.DB.prepare(`SELECT 1 FROM ${ident(kind)} WHERE ${ident(uc)}=? AND ${ident(tc)}=? LIMIT 1`).bind(a.user.id,target).first();if(ex){await env.DB.prepare(`DELETE FROM ${ident(kind)} WHERE ${ident(uc)}=? AND ${ident(tc)}=?`).bind(a.user.id,target).run();return json({active:false},200,ch);}await insert(env.DB,kind,{id:newId(),blocker_id:a.user.id,muter_id:a.user.id,user_id:a.user.id,from_user_id:a.user.id,blocked_id:target,muted_id:target,target_user_id:target,to_user_id:target,created_at:now()});return json({active:true},201,ch);}}
if(path==='/messages'&&req.method==='POST'){requireAuth(a);const b=await body(),target=text(b.recipient_id||b.user_id),content=text(b.content).trim().slice(0,4000);if(!target||!content)return json({error:'Recipient and message are required'},400,ch);const pc=await columns(env.DB,'conversation_participants'),conv=first(pc,['conversation_id']),uc=first(pc,['user_id','participant_id']);if(!conv||!uc)return json({error:'Messages unavailable'},503,ch);let cid=text((await env.DB.prepare(`SELECT p1.${ident(conv)} AS cid FROM conversation_participants p1 JOIN conversation_participants p2 ON p1.${ident(conv)}=p2.${ident(conv)} WHERE p1.${ident(uc)}=? AND p2.${ident(uc)}=? LIMIT 1`).bind(a.user.id,target).first<Row>())?.cid);if(!cid){cid=newId();await insert(env.DB,'conversations',{id:cid,conversation_id:cid,created_at:now(),updated_at:now()});await insert(env.DB,'conversation_participants',{id:newId(),conversation_id:cid,user_id:a.user.id,participant_id:a.user.id,created_at:now()});await insert(env.DB,'conversation_participants',{id:newId(),conversation_id:cid,user_id:target,participant_id:target,created_at:now()});}const mc=await columns(env.DB,'messages'),cc=first(mc,['conversation_id']),sc=first(mc,['sender_id','user_id','from_user_id']),bc=first(mc,['content','body','message']);if(!cc||!sc||!bc)return json({error:'Messages unavailable'},503,ch);const mid=newId();await insert(env.DB,'messages',{id:mid,message_id:mid,conversation_id:cid,sender_id:a.user.id,user_id:a.user.id,from_user_id:a.user.id,content,body:content,created_at:now(),read_at:null,is_read:0});await notify(env.DB,target,a.user.id,'message',cid);return json({conversation_id:cid,message_id:mid},201,ch);}
if(path==='/messages'&&req.method==='GET'){requireAuth(a);const cid=text(url.searchParams.get('conversation_id'));if(!cid)return json({messages:[]},200,ch);const pc=await columns(env.DB,'conversation_participants'),conv=first(pc,['conversation_id']),uc=first(pc,['user_id','participant_id']);if(!conv||!uc)return json({messages:[]},200,ch);const member=await env.DB.prepare(`SELECT 1 FROM conversation_participants WHERE ${ident(conv)}=? AND ${ident(uc)}=? LIMIT 1`).bind(cid,a.user.id).first();if(!member)return json({error:'Forbidden'},403,ch);const mc=await columns(env.DB,'messages'),cc=first(mc,['conversation_id']);if(!cc)return json({messages:[]},200,ch);const r=await env.DB.prepare(`SELECT * FROM messages WHERE ${ident(cc)}=? ORDER BY created_at ASC LIMIT 200`).bind(cid).all<Row>();return json({messages:r.results||[]},200,ch);}
if(path==='/earn/offers'&&req.method==='GET'){requireAuth(a);const r=await env.DB.prepare("SELECT * FROM reward_offers WHERE status IS NULL OR lower(status) IN ('active','enabled','live') ORDER BY created_at DESC LIMIT 100").all<Row>().catch(()=>({results:[]}));return json({offers:r.results||[]},200,ch);}
if(path==='/wallet'&&req.method==='GET'){requireAuth(a);const c=await columns(env.DB,'wallets'),uc=first(c,['user_id','owner_id']);if(!uc)return json({wallet:null,transactions:[]},200,ch);const wallet=await env.DB.prepare(`SELECT * FROM wallets WHERE ${ident(uc)}=? LIMIT 1`).bind(a.user.id).first<Row>();let transactions:Row[]=[];try{const t=await columns(env.DB,'wallet_transactions'),wc=first(t,['wallet_id','user_id','owner_id']);if(wc)transactions=(await env.DB.prepare(`SELECT * FROM wallet_transactions WHERE ${ident(wc)}=? ORDER BY created_at DESC LIMIT 100`).bind(wallet?.id||a.user.id).all<Row>()).results||[];}catch{}return json({wallet,transactions},200,ch);}
return json({error:'Not found'},404,ch);}
export default {async fetch(req:Request,env:Env){try{return await handle(env,req);}catch(e){const status=Number((e as any)?.status)||500;return json({error:status===401?'Authentication required':status<500?text((e as any)?.message):'Internal server error'},status);}}};
