export interface Env {
  DB: D1Database;
  R2: R2Bucket;
  JWT_SECRET?: string;
  JWT_REFRESH_SECRET?: string;
  BREVO_API_KEY?: string;
  BREVO_FROM_EMAIL?: string;
  FRONTEND_ORIGIN?: string;
  OFFERWALL_PROVIDER?: string;
  OFFERWALL_SECRET?: string;
  PAYSTACK_SECRET_KEY?: string;
  PAYPAL_CLIENT_ID?: string;
  PAYPAL_CLIENT_SECRET?: string;
  MUSIC_PROVIDER_URL?: string;
}

type Row = Record<string, unknown>;
type User = { id: string; username: string; email: string; avatar_url?: string | null; bio?: string | null; status?: string | null };
type Auth = { user: User; sid: string; rotated: boolean; tokens?: Tokens };
type Tokens = { access: string; refresh: string; aexp: number; rexp: number; sid: string };
const TABLES = new Set(['users','user_sessions','password_reset_tokens','security_events','user_settings','notification_preferences','follows','blocks','mutes','posts','post_media','post_likes','saved_posts','comments','comment_likes','mentions','notifications','reward_offers','offerwall_events','reward_transactions','wallets','wallet_transactions','payment_providers','payment_transactions','withdrawals','withdrawal_attempts','admin_users','reports','moderation_actions','conversations','conversation_participants','messages']);
const enc = new TextEncoder(); const now=()=>Math.floor(Date.now()/1000); const newId=()=>crypto.randomUUID();
const text=(v:unknown)=>typeof v==='string'?v:v==null?'':String(v); const ident=(v:string)=>{if(!/^[A-Za-z_][A-Za-z0-9_]*$/.test(v))throw new Error('unsafe identifier');return `"${v}"`;}; const first=(s:Set<string>,names:string[])=>names.find(n=>s.has(n));
const json=(data:unknown,status=200,headers:HeadersInit={})=>{const h=new Headers(headers);h.set('content-type','application/json; charset=utf-8');h.set('cache-control','no-store');return new Response(JSON.stringify(data),{status,headers:h});};
function cors(env:Env,req:Request):HeadersInit{const h=new Headers(),origin=req.headers.get('Origin');if(origin&&env.FRONTEND_ORIGIN&&origin===env.FRONTEND_ORIGIN){h.set('access-control-allow-origin',origin);h.set('vary','Origin');h.set('access-control-allow-credentials','true');}h.set('access-control-allow-methods','GET,POST,PATCH,DELETE,OPTIONS');h.set('access-control-allow-headers','content-type,x-sphere-signature,x-sphere-timestamp,idempotency-key');return h;}
async function columns(db:D1Database,name:string){if(!TABLES.has(name))throw new Error('unknown table');const r=await db.prepare(`PRAGMA table_info(${ident(name)})`).all<Row>();return new Set((r.results||[]).map(x=>text(x.name)));}
async function insert(db:D1Database,name:string,values:Record<string,unknown>){const c=await columns(db,name),e=Object.entries(values).filter(([k,v])=>c.has(k)&&v!==undefined);if(!e.length)throw new Error(`No compatible columns for ${name}`);return db.prepare(`INSERT INTO ${ident(name)} (${e.map(([k])=>ident(k)).join(',')}) VALUES (${e.map(()=>'?').join(',')})`).bind(...e.map(([,v])=>v)).run();}
async function insertStmt(db:D1Database,name:string,values:Record<string,unknown>){const c=await columns(db,name),e=Object.entries(values).filter(([k,v])=>c.has(k)&&v!==undefined);if(!e.length)throw new Error(`No compatible columns for ${name}`);return db.prepare(`INSERT INTO ${ident(name)} (${e.map(([k])=>ident(k)).join(',')}) VALUES (${e.map(()=>'?').join(',')})`).bind(...e.map(([,v])=>v));}
async function update(db:D1Database,name:string,where:string,args:unknown[],values:Record<string,unknown>){const c=await columns(db,name),e=Object.entries(values).filter(([k,v])=>c.has(k)&&v!==undefined);if(!e.length)throw new Error(`No compatible columns for ${name}`);return db.prepare(`UPDATE ${ident(name)} SET ${e.map(([k])=>`${ident(k)}=?`).join(',')} WHERE ${where}`).bind(...e.map(([,v])=>v),...args).run();}
function cookie(name:string,value:string,maxAge:number){return `${name}=${value}; Path=/; Max-Age=${maxAge}; HttpOnly; Secure; SameSite=None`;} function clearCookie(name:string){return `${name}=; Path=/; Max-Age=0; HttpOnly; Secure; SameSite=None`;}
function parseCookies(req:Request){return Object.fromEntries((req.headers.get('cookie')||'').split(';').map(x=>x.trim()).filter(Boolean).map(x=>{const i=x.indexOf('=');return [x.slice(0,i),x.slice(i+1)]}));}
function b64(bytes:ArrayBuffer|Uint8Array){const view=bytes instanceof Uint8Array?bytes:new Uint8Array(bytes);return btoa(String.fromCharCode(...view)).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');} function unb64(s:string){const p=s.replaceAll('-','+').replaceAll('_','/'),pad='='.repeat((4-p.length%4)%4);return Uint8Array.from(atob(p+pad),c=>c.charCodeAt(0));}
async function sha(v:string){return b64(await crypto.subtle.digest('SHA-256',enc.encode(v)));} async function hmac(secret:string,v:string){const k=await crypto.subtle.importKey('raw',enc.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return b64(await crypto.subtle.sign('HMAC',k,enc.encode(v)));}
async function signJwt(secret:string,p:Record<string,unknown>){const h=b64(enc.encode(JSON.stringify({alg:'HS256',typ:'JWT'}))),b=b64(enc.encode(JSON.stringify(p)));return `${h}.${b}.${await hmac(secret,`${h}.${b}`)}`;}
async function verifyJwt(secret:string,t:string){try{const [h,p,s]=t.split('.');if(!h||!p||!s||await hmac(secret,`${h}.${p}`)!==s)return null;const v=JSON.parse(new TextDecoder().decode(unb64(p)));return typeof v.exp==='number'&&v.exp<=now()?null:v;}catch{return null;}}
function randomToken(n=32){const a=new Uint8Array(n);crypto.getRandomValues(a);return [...a].map(x=>x.toString(16).padStart(2,'0')).join('');}
async function passwordHash(password:string,salt=randomToken(16)){const k=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt:enc.encode(salt),iterations:100000,hash:'SHA-256'},k,256);return `100000$${salt}$${b64(bits)}`;} async function passwordOk(password:string,stored:string){const p=stored.split('$');return p.length===3&&(await passwordHash(password,p[1]))===stored;}
const rowId=(r:Row)=>text(r.id??r.user_id); const rowPassword=(r:Row)=>text(r.password_hash??r.password_digest??r.password??'');
async function getUser(db:D1Database,id:string):Promise<User|null>{const c=await columns(db,'users'),ic=first(c,['id','user_id']),un=first(c,['username','handle','name']),em=first(c,['email','email_address']),av=first(c,['avatar_url','avatar','profile_image_url']),bio=first(c,['bio','about']),st=first(c,['status','account_status']);if(!ic)throw new Error('users id missing');const s=[`${ident(ic)} AS id`,un?`${ident(un)} AS username`:"'' AS username",em?`${ident(em)} AS email`:"'' AS email"];if(av)s.push(`${ident(av)} AS avatar_url`);if(bio)s.push(`${ident(bio)} AS bio`);if(st)s.push(`${ident(st)} AS status`);return await db.prepare(`SELECT ${s.join(',')} FROM users WHERE ${ident(ic)}=? LIMIT 1`).bind(id).first<User>();}
async function findUser(db:D1Database,v:string){const c=await columns(db,'users'),ic=first(c,['id','user_id']),em=first(c,['email','email_address']),un=first(c,['username','handle']);if(em&&un)return db.prepare(`SELECT * FROM users WHERE lower(${ident(em)})=lower(?) OR lower(${ident(un)})=lower(?) LIMIT 1`).bind(v,v).first<Row>();if(em)return db.prepare(`SELECT * FROM users WHERE lower(${ident(em)})=lower(?) LIMIT 1`).bind(v).first<Row>();if(un)return db.prepare(`SELECT * FROM users WHERE lower(${ident(un)})=lower(?) LIMIT 1`).bind(v).first<Row>();if(ic)return db.prepare(`SELECT * FROM users WHERE ${ident(ic)}=? LIMIT 1`).bind(v).first<Row>();return null;}
async function createTokens(env:Env,userId:string){if(!env.JWT_SECRET||!env.JWT_REFRESH_SECRET)throw new Error('Authentication configuration unavailable');const sid=newId(),rawRefresh=randomToken(32),hash=await sha(rawRefresh),aexp=now()+900,rexp=now()+2592000;await insert(env.DB,'user_sessions',{id:sid,user_id:userId,refresh_token_hash:hash,token_hash:hash,session_token_hash:hash,created_at:now(),expires_at:rexp,revoked_at:null});const access=await signJwt(env.JWT_SECRET,{sub:userId,sid,typ:'access',exp:aexp}),refresh=await signJwt(env.JWT_REFRESH_SECRET,{sub:userId,sid,typ:'refresh',jti:rawRefresh,exp:rexp});return {access,refresh,aexp,rexp,sid};}
async function revokeSession(env:Env,sid:string){const c=await columns(env.DB,'user_sessions'),ic=first(c,['id','session_id']),rc=first(c,['revoked_at','invalidated_at']);if(ic&&rc)await update(env.DB,'user_sessions',`${ident(ic)}=?`,[sid],{[rc]:now()});}
async function auth(env:Env,req:Request):Promise<Auth|null>{if(!env.JWT_SECRET||!env.JWT_REFRESH_SECRET)return null;const c=parseCookies(req),access=c.sphere_access?await verifyJwt(env.JWT_SECRET,c.sphere_access):null;if(access?.typ==='access'&&access.sub){const user=await getUser(env.DB,text(access.sub));if(user&&!(user.status&&['banned','disabled','suspended'].includes(user.status.toLowerCase())))return {user,sid:text(access.sid),rotated:false};}const r=c.sphere_refresh?await verifyJwt(env.JWT_REFRESH_SECRET,c.sphere_refresh):null;if(r?.typ!=='refresh'||!r.sub||!r.sid||!r.jti)return null;const h=await sha(text(r.jti)),cols=await columns(env.DB,'user_sessions'),ic=first(cols,['id','session_id']),hc=first(cols,['refresh_token_hash','token_hash','session_token_hash']);if(!ic||!hc)return null;const live=await env.DB.prepare(`SELECT 1 FROM user_sessions WHERE ${ident(ic)}=? AND ${ident(hc)}=? AND (revoked_at IS NULL OR revoked_at=0) LIMIT 1`).bind(text(r.sid),h).first();if(!live)return null;const user=await getUser(env.DB,text(r.sub));if(!user)return null;await revokeSession(env,text(r.sid));const tokens=await createTokens(env,text(r.sub));return {user,sid:tokens.sid,rotated:true,tokens};}
function requireAuth(a:Auth|null):asserts a{if(!a)throw Object.assign(new Error('Authentication required'),{status:401});} function setTokens(h:Headers,t:Tokens){h.append('set-cookie',cookie('sphere_access',t.access,Math.max(1,t.aexp-now())));h.append('set-cookie',cookie('sphere_refresh',t.refresh,Math.max(1,t.rexp-now())));} function clearTokens(h:Headers){h.append('set-cookie',clearCookie('sphere_access'));h.append('set-cookie',clearCookie('sphere_refresh'));}
async function securityEvent(env:Env,event:string,userId?:string,req?:Request,meta?:Record<string,unknown>){try{const ip=req?.headers.get('CF-Connecting-IP')||req?.headers.get('X-Forwarded-For')?.split(',')[0]?.trim(),ua=req?.headers.get('User-Agent');await insert(env.DB,'security_events',{id:newId(),user_id:userId,event_type:event,type:event,ip_address:ip,ip,user_agent:ua,metadata:meta?JSON.stringify(meta):undefined,created_at:now()});}catch{}}
async function rateLimit(env:Env,req:Request,key:string,limit:number,windowSec:number){try{const c=await columns(env.DB,'security_events'),tc=first(c,['created_at','occurred_at','timestamp']);if(!tc)return true;const ec=first(c,['event_type','type','event']),ic=first(c,['ip_address','ip','client_ip']),ip=req.headers.get('CF-Connecting-IP')||req.headers.get('X-Forwarded-For')?.split(',')[0]?.trim()||'unknown',clauses=[`${ident(tc)}> ?`],args:unknown[]=[now()-windowSec];if(ec){clauses.push(`${ident(ec)}=?`);args.push(`rate:${key}`);}if(ic){clauses.push(`${ident(ic)}=?`);args.push(ip);}const r=await env.DB.prepare(`SELECT COUNT(*) AS n FROM security_events WHERE ${clauses.join(' AND ')}`).bind(...args).first<Row>();if(Number(r?.n||0)>=limit)return false;await insert(env.DB,'security_events',{id:newId(),event_type:`rate:${key}`,type:`rate:${key}`,ip_address:ip,ip,created_at:now()});return true;}catch{return true;}}
async function notify(env:Env,recipient:string,actor:string,type:string,entity?:string,message?:string){try{await insert(env.DB,'notifications',{id:newId(),user_id:recipient,recipient_id:recipient,actor_id:actor,type,entity_id:entity,reference_id:entity,message,created_at:now(),read_at:null,is_read:0});}catch{}}
async function mentionText(env:Env,actor:string,content:string,entity:string,entityType:'post'|'comment'){const names=[...content.matchAll(/@([a-z0-9_.]{3,30})/gi)].map(m=>m[1].toLowerCase()).filter((v,i,a)=>a.indexOf(v)===i);for(const username of names){const u=await findUser(env.DB,username);if(!u||rowId(u)===actor)continue;const values:Record<string,unknown>={id:newId(),mentioned_user_id:rowId(u),user_id:rowId(u),actor_id:actor,created_at:now()};values[entityType==='post'?'post_id':'comment_id']=entity;try{await insert(env.DB,'mentions',values);}catch{}await notify(env,rowId(u),actor,'mention',entity,`@${username} mentioned you`);}}
async function sendBrevo(env:Env,email:string,token:string){if(!env.BREVO_API_KEY||!env.BREVO_FROM_EMAIL||!env.FRONTEND_ORIGIN)return false;const r=await fetch('https://api.brevo.com/v3/smtp/email',{method:'POST',headers:{'content-type':'application/json','api-key':env.BREVO_API_KEY},body:JSON.stringify({sender:{email:env.BREVO_FROM_EMAIL},to:[{email}],subject:'Reset your Sphere password',htmlContent:`<p>Reset your Sphere password.</p><p><a href="${env.FRONTEND_ORIGIN}/reset-password?token=${encodeURIComponent(token)}">Reset password</a></p>`})});return r.ok;}
async function settingRow(env:Env,userId:string){try{const c=await columns(env.DB,'user_settings'),uc=first(c,['user_id','owner_id']);return uc?await env.DB.prepare(`SELECT * FROM user_settings WHERE ${ident(uc)}=? LIMIT 1`).bind(userId).first<Row>():null;}catch{return null;}}
async function blocked(env:Env,a:string,b:string){try{const c=await columns(env.DB,'blocks'),uc=first(c,['blocker_id','user_id','from_user_id']),tc=first(c,['blocked_id','target_user_id','to_user_id']);if(uc&&tc)return Boolean(await env.DB.prepare(`SELECT 1 FROM blocks WHERE ${ident(uc)}=? AND ${ident(tc)}=? LIMIT 1`).bind(a,b).first());}catch{}return false;}
async function canMessage(env:Env,a:string,b:string){if(await blocked(env,a,b)||await blocked(env,b,a))return false;const s=await settingRow(env,b);if(!s)return true;const c=await columns(env.DB,'user_settings'),k=first(c,['allow_messages']);return !k||Boolean(s[k]??true);}
async function isAdmin(env:Env,userId:string){try{const c=await columns(env.DB,'admin_users'),uc=first(c,['user_id','admin_id']),role=first(c,['role','admin_role']),status=first(c,['status','state']);if(!uc)return false;const r=await env.DB.prepare(`SELECT * FROM admin_users WHERE ${ident(uc)}=? LIMIT 1`).bind(userId).first<Row>();if(!r)return false;if(status&&['disabled','revoked','inactive'].includes(text(r[status]).toLowerCase()))return false;return !role||['admin','moderator','superadmin','owner'].includes(text(r[role]).toLowerCase());}catch{return false;}}
function requireId(v:string,name:string){if(!/^[A-Za-z0-9_-]{1,120}$/.test(v))throw Object.assign(new Error(`Invalid ${name}`),{status:400});return v;}
async function walletInfo(env:Env,userId:string){const c=await columns(env.DB,'wallets'),uc=first(c,['user_id','owner_id']);if(!uc)return {wallet:null,transactions:[] as Row[]};let wallet=await env.DB.prepare(`SELECT * FROM wallets WHERE ${ident(uc)}=? LIMIT 1`).bind(userId).first<Row>();if(!wallet){try{const id=newId();await insert(env.DB,'wallets',{id,wallet_id:id,user_id:userId,owner_id:userId,available_balance:0,balance:0,pending_balance:0,currency:'NGN',created_at:now(),updated_at:now()});wallet=await env.DB.prepare(`SELECT * FROM wallets WHERE ${ident(uc)}=? LIMIT 1`).bind(userId).first<Row>();}catch{}}let transactions:Row[]=[];try{const t=await columns(env.DB,'wallet_transactions'),wc=first(t,['wallet_id','user_id','owner_id']);if(wc)transactions=(await env.DB.prepare(`SELECT * FROM wallet_transactions WHERE ${ident(wc)}=? ORDER BY created_at DESC LIMIT 100`).bind(wallet?.id||userId).all<Row>()).results||[];}catch{}return {wallet,transactions};}
async function balanceColumn(db:D1Database){const c=await columns(db,'wallets');return {available:first(c,['available_balance','balance_available','balance']),pending:first(c,['pending_balance','balance_pending'])};}
async function rewardCredit(env:Env,userId:string,amount:number,provider:string,eventId:string,offerId?:string){if(!Number.isFinite(amount)||amount<=0||amount>100000000)return {ok:false,status:400,error:'Invalid reward amount'};const ec=await columns(env.DB,'offerwall_events'),eventKey=first(ec,['event_id','external_event_id','reference_id','transaction_id']);if(!eventKey)return {ok:false,status:503,error:'Reward events unavailable'};const exists=await env.DB.prepare(`SELECT 1 FROM offerwall_events WHERE ${ident(eventKey)}=? LIMIT 1`).bind(eventId).first();if(exists)return {ok:true,duplicate:true};const wc=await columns(env.DB,'wallets'),uc=first(wc,['user_id','owner_id']),bc=await balanceColumn(env.DB);if(!uc||!bc.available)return {ok:false,status:503,error:'Wallet balance unavailable'};const wallet=await env.DB.prepare(`SELECT * FROM wallets WHERE ${ident(uc)}=? LIMIT 1`).bind(userId).first<Row>();if(!wallet)return {ok:false,status:409,error:'Wallet unavailable'};const wid=text(wallet.id??wallet.wallet_id??userId),current=Number(wallet[bc.available]??0),next=current+amount;const statements=[await insertStmt(env.DB,'offerwall_events',{id:newId(),event_id:eventId,external_event_id:eventId,provider,provider_name:provider,user_id:userId,offer_id:offerId,status:'accepted',state:'accepted',amount,created_at:now(),processed_at:now()}),await insertStmt(env.DB,'reward_transactions',{id:newId(),user_id:userId,offer_id:offerId,offerwall_event_id:eventId,event_id:eventId,provider,type:'credit',status:'approved',state:'approved',amount,created_at:now()}),await insertStmt(env.DB,'wallet_transactions',{id:newId(),wallet_id:wid,user_id:userId,type:'reward',transaction_type:'reward',direction:'credit',amount,balance_after:next,status:'completed',reference_id:eventId,created_at:now()}),env.DB.prepare(`UPDATE wallets SET ${ident(bc.available)}=?${bc.pending?`, ${ident(bc.pending)}=COALESCE(${ident(bc.pending)},0)`:''} WHERE ${ident(uc)}=?`).bind(next,userId)];try{await env.DB.batch(statements);return {ok:true,duplicate:false};}catch{return {ok:false,status:409,error:'Reward event could not be committed'};}}
async function validatePostback(env:Env,req:Request,raw:string){if(!env.OFFERWALL_SECRET)return false;const ts=req.headers.get('x-sphere-timestamp')||'',sig=req.headers.get('x-sphere-signature')||'',t=Number(ts);if(!/^\d+$/.test(ts)||!Number.isFinite(t)||Math.abs(now()-t)>300||!sig)return false;return (await hmac(env.OFFERWALL_SECRET,`${ts}.${raw}`))===sig;}
async function handle(env:Env,req:Request){const url=new URL(req.url),path=url.pathname.replace(/\/+$/,'')||'/';if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(env,req)});const ch=cors(env,req),body=async()=>req.headers.get('content-type')?.includes('application/json')?await req.json<Record<string,unknown>>():{};if(path==='/health')return json({ok:true,service:'sphere-api',database:'D1',storage:'R2'},200,ch);let a=await auth(env,req);
if(path==='/auth/signup'&&req.method==='POST'){if(!await rateLimit(env,req,'signup',8,3600))return json({error:'Too many signup attempts'},429,ch);const b=await body(),username=text(b.username).trim().toLowerCase(),email=text(b.email).trim().toLowerCase(),password=text(b.password);if(!/^[a-z0-9_.]{3,30}$/.test(username)||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||password.length<8)return json({error:'Invalid signup details'},400,ch);if(await findUser(env.DB,username)||await findUser(env.DB,email))return json({error:'Unable to create account with those details'},409,ch);const ph=await passwordHash(password),id=newId();await insert(env.DB,'users',{id,username,email,password_hash:ph,role:'USER',status:'ACTIVE',created_at:now(),updated_at:now()});await securityEvent(env,'signup',id,req);const t=await createTokens(env,id),h=new Headers(ch);setTokens(h,t);return json({user:await getUser(env.DB,id)},201,h);}
if(path==='/auth/login'&&req.method==='POST'){if(!await rateLimit(env,req,'login',15,900))return json({error:'Too many login attempts'},429,ch);const b=await body(),v=text(b.email||b.username).trim().toLowerCase(),password=text(b.password),r=await findUser(env.DB,v);if(!r||!(await passwordOk(password,rowPassword(r)))){await securityEvent(env,'login_failed',undefined,req);return json({error:'Invalid email/username or password'},401,ch);}const t=await createTokens(env,rowId(r));await securityEvent(env,'login',rowId(r),req);const h=new Headers(ch);setTokens(h,t);return json({user:await getUser(env.DB,rowId(r))},200,h);}
if(path==='/auth/session'&&req.method==='GET'){if(!a)return json({user:null},200,ch);if(a.rotated&&a.tokens){const h=new Headers(ch);setTokens(h,a.tokens);return json({user:a.user},200,h);}return json({user:a.user},200,ch);}
if(path==='/auth/refresh'&&req.method==='POST'){if(!a?.rotated||!a.tokens)return json({error:'Refresh required'},401,ch);const h=new Headers(ch);setTokens(h,a.tokens);return json({user:a.user},200,h);}
if(path==='/auth/logout'&&req.method==='POST'){if(a){await revokeSession(env,a.sid);await securityEvent(env,'logout',a.user.id,req);}const h=new Headers(ch);clearTokens(h);return json({ok:true},200,h);}
if(path==='/auth/forgot-password'&&req.method==='POST'){if(!await rateLimit(env,req,'password_reset',5,3600))return json({error:'Too many reset requests'},429,ch);const b=await body(),email=text(b.email).trim().toLowerCase(),r=await findUser(env.DB,email);if(r){const token=randomToken(32),hash=await sha(token);await insert(env.DB,'password_reset_tokens',{id:newId(),user_id:rowId(r),token_hash:hash,token_digest:hash,expires_at:now()+3600,created_at:now(),used_at:null});await sendBrevo(env,email,token);await securityEvent(env,'password_reset_requested',rowId(r),req);}return json({ok:true,message:'If that account exists, a reset email has been sent.'},200,ch);}
if(path==='/auth/reset-password'&&req.method==='POST'){if(!await rateLimit(env,req,'password_reset_complete',8,3600))return json({error:'Too many reset attempts'},429,ch);const b=await body(),token=text(b.token),password=text(b.password);if(token.length<20||password.length<8)return json({error:'Invalid reset request'},400,ch);const c=await columns(env.DB,'password_reset_tokens'),tc=first(c,['token_hash','token_digest','token']),uc=first(c,['user_id']),ec=first(c,['expires_at','expires']),used=first(c,['used_at','used']);if(!tc||!uc)return json({error:'Reset unavailable'},503,ch);const hash=await sha(token),conds=[`${ident(tc)}=?`],args:unknown[]=[hash];if(ec){conds.push(`${ident(ec)}> ?`);args.push(now());}if(used)conds.push(`(${ident(used)} IS NULL OR ${ident(used)}=0)`);const r=await env.DB.prepare(`SELECT ${ident(uc)} AS user_id FROM password_reset_tokens WHERE ${conds.join(' AND ')} LIMIT 1`).bind(...args).first<Row>();if(!r)return json({error:'Invalid or expired reset token'},400,ch);const ph=await passwordHash(password),ucols=await columns(env.DB,'users'),ic=first(ucols,['id','user_id']);if(!ic)return json({error:'Reset unavailable'},503,ch);await update(env.DB,'users',`${ident(ic)}=?`,[text(r.user_id)],{password_hash:ph,password_digest:ph,updated_at:now()});if(used)await update(env.DB,'password_reset_tokens',`${ident(tc)}=?`,[hash],{[used]:now()});await securityEvent(env,'password_reset_completed',text(r.user_id),req);return json({ok:true},200,ch);}
if(path==='/me'&&req.method==='GET'){requireAuth(a);return json({user:a.user},200,ch);}if(path==='/me'&&req.method==='PATCH'){requireAuth(a);const b=await body(),username=text(b.username).trim().toLowerCase(),bio=text(b.bio).slice(0,500),avatar=text(b.avatar_url);if(username&&!/^[a-z0-9_.]{3,30}$/.test(username))return json({error:'Invalid username'},400,ch);if(username&&username!==a.user.username){const r=await findUser(env.DB,username);if(r&&rowId(r)!==a.user.id)return json({error:'Username already in use'},409,ch);}const c=await columns(env.DB,'users'),ic=first(c,['id','user_id']);if(!ic)return json({error:'Profile unavailable'},503,ch);await update(env.DB,'users',`${ident(ic)}=?`,[a.user.id],{username:username||undefined,bio,avatar_url:avatar||undefined,updated_at:now()});return json({user:await getUser(env.DB,a.user.id)},200,ch);}
if(path==='/upload/image'&&req.method==='POST'){requireAuth(a);if(!await rateLimit(env,req,'image_upload',30,3600))return json({error:'Upload limit reached'},429,ch);const form=await req.formData(),file=form.get('file');if(!(file instanceof File))return json({error:'Image file required'},400,ch);if(file.size>10*1024*1024)return json({error:'Image exceeds 10 MB'},413,ch);const types:{[k:string]:string}={'image/jpeg':'jpg','image/png':'png','image/webp':'webp','image/gif':'gif'},ext=types[file.type.toLowerCase()];if(!ext)return json({error:'Only JPEG, PNG, WebP and GIF images are supported'},415,ch);const key=`users/${a.user.id}/images/${newId()}.${ext}`;await env.R2.put(key,file.stream(),{httpMetadata:{contentType:file.type.toLowerCase(),cacheControl:'public, max-age=31536000, immutable'},customMetadata:{owner_id:a.user.id}});return json({key},201,ch);}
if(path.startsWith('/media/')&&req.method==='GET'){const key=decodeURIComponent(path.slice(7));if(!/^users\/[^/]+\/images\/[A-Za-z0-9-]+\.(jpg|png|webp|gif)$/.test(key))return new Response('Not found',{status:404});const obj=await env.R2.get(key);if(!obj)return new Response('Not found',{status:404});return new Response(obj.body,{headers:{'content-type':obj.httpMetadata?.contentType||'application/octet-stream','cache-control':'public, max-age=31536000, immutable'}});}
if(path==='/posts'&&req.method==='GET'){requireAuth(a);const limit=Math.min(Math.max(Number(url.searchParams.get('limit')||20),1),50),offset=Math.max(Number(url.searchParams.get('offset')||0),0),rows=await env.DB.prepare('SELECT * FROM posts ORDER BY created_at DESC LIMIT ? OFFSET ?').bind(limit,offset).all<Row>(),posts=[];const pc=await columns(env.DB,'posts'),ac=first(pc,['user_id','author_id','creator_id']);for(const r of rows.results||[]){const pid=rowId(r),owner=ac?text(r[ac]):'';if(owner&&await blocked(env,a.user.id,owner))continue;let media=null;try{const m=await columns(env.DB,'post_media'),mp=first(m,['post_id']);if(mp)media=await env.DB.prepare(`SELECT * FROM post_media WHERE ${ident(mp)}=? LIMIT 1`).bind(pid).first<Row>();}catch{}const author=owner?await getUser(env.DB,owner):null;let like_count=0,liked=false,saved=false;try{const l=await columns(env.DB,'post_likes'),lp=first(l,['post_id']),lu=first(l,['user_id','actor_id']);if(lp){const n=await env.DB.prepare(`SELECT COUNT(*) AS n FROM post_likes WHERE ${ident(lp)}=?`).bind(pid).first<Row>();like_count=Number(n?.n||0);if(lu)liked=Boolean(await env.DB.prepare(`SELECT 1 FROM post_likes WHERE ${ident(lp)}=? AND ${ident(lu)}=? LIMIT 1`).bind(pid,a.user.id).first());}}catch{}try{const s=await columns(env.DB,'saved_posts'),sp=first(s,['post_id']),su=first(s,['user_id','actor_id']);if(sp&&su)saved=Boolean(await env.DB.prepare(`SELECT 1 FROM saved_posts WHERE ${ident(sp)}=? AND ${ident(su)}=? LIMIT 1`).bind(pid,a.user.id).first());}catch{}posts.push({...r,id:pid,author,media,like_count,liked,saved});}return json({posts},200,ch);}
if(path==='/posts'&&req.method==='POST'){requireAuth(a);const b=await body(),caption=text(b.caption).slice(0,2200),key=text(b.imageKey),musicObj=typeof b.music==='object'&&b.music?b.music as Record<string,unknown>:null;if(!key||!key.startsWith(`users/${a.user.id}/images/`))return json({error:'Owned image is required'},400,ch);const obj=await env.R2.head(key);if(!obj)return json({error:'Image was not found'},400,ch);const pid=newId();const song_title=text(musicObj?.title||musicObj?.song_title).slice(0,300)||null;const song_artist=text(musicObj?.artist||musicObj?.song_artist).slice(0,300)||null;const song_url=text(musicObj?.external_url||musicObj?.song_url).slice(0,1000)||null;await insert(env.DB,'posts',{id:pid,user_id:a.user.id,caption,song_title,song_artist,song_url,created_at:now(),updated_at:now()});try{await insert(env.DB,'post_media',{id:newId(),post_id:pid,media_type:'image',storage_key:key,mime_type:obj.httpMetadata?.contentType||null,file_size:obj.size,created_at:now()});}catch{await env.DB.prepare('DELETE FROM posts WHERE id=?').bind(pid).run();return json({error:'Unable to persist post media'},500,ch);}await mentionText(env,a.user.id,caption,pid,'post');return json({post_id:pid},201,ch);}
const act=path.match(/^\/posts\/([^/]+)\/(like|save)$/);if(act&&req.method==='POST'){requireAuth(a);const pid=requireId(decodeURIComponent(act[1]),'post id'),post=await env.DB.prepare('SELECT * FROM posts WHERE id=? LIMIT 1').bind(pid).first<Row>();if(!post)return json({error:'Post not found'},404,ch);const owner=rowId(post);if(owner&&await blocked(env,a.user.id,owner))return json({error:'Forbidden'},403,ch);const type=act[2],table=type==='like'?'post_likes':'saved_posts',c=await columns(env.DB,table),pc=first(c,['post_id']),uc=first(c,['user_id','actor_id']);if(!pc||!uc)return json({error:'Unavailable'},503,ch);const ex=await env.DB.prepare(`SELECT 1 FROM ${ident(table)} WHERE ${ident(pc)}=? AND ${ident(uc)}=? LIMIT 1`).bind(pid,a.user.id).first();if(ex){await env.DB.prepare(`DELETE FROM ${ident(table)} WHERE ${ident(pc)}=? AND ${ident(uc)}=?`).bind(pid,a.user.id).run();return json({[type==='like'?'liked':'saved']:false},200,ch);}await insert(env.DB,table,{id:newId(),post_id:pid,user_id:a.user.id,actor_id:a.user.id,created_at:now()});if(type==='like'&&owner&&owner!==a.user.id)await notify(env,owner,a.user.id,'like',pid);return json({[type==='like'?'liked':'saved']:true},200,ch);}
if(path.startsWith('/posts/')&&req.method==='DELETE'){
  requireAuth(a);
  const pid=decodeURIComponent(path.slice('/posts/'.length));
  if(!pid)return json({error:'Post id is required'},400,ch);
  const pc=await columns(env.DB,'posts');
  const idc=first(pc,['id','post_id']);
  const uc=first(pc,['user_id','author_id','creator_id']);
  if(!idc||!uc)return json({error:'Post schema unavailable'},500,ch);
  const post=await env.DB.prepare(`SELECT * FROM posts WHERE ${ident(idc)}=? LIMIT 1`).bind(pid).first<Row>();
  if(!post)return json({error:'Post not found'},404,ch);
  if(text(post[uc])!==a.user.id)return json({error:'Forbidden'},403,ch);
  await env.DB.prepare(`DELETE FROM posts WHERE ${ident(idc)}=?`).bind(pid).run();
  return json({ok:true},200,ch);
}
if(path.startsWith('/posts/')&&path.endsWith('/comments')&&req.method==='GET'){
 requireAuth(a);
 const pid=requireId(decodeURIComponent(path.slice(7,-9)),'post id');
 const post=await env.DB.prepare('SELECT * FROM posts WHERE id=? LIMIT 1').bind(pid).first<Row>();
 if(!post)return json({error:'Post not found'},404,ch);
 const owner=rowId(post);
 if(await blocked(env,a.user.id,owner))return json({error:'Forbidden'},403,ch);
 const c=await columns(env.DB,'comments');
 const pc=first(c,['post_id']),uc=first(c,['user_id','author_id']),cc=first(c,['content','body']);
 if(!pc||!uc||!cc)return json({error:'Comments unavailable'},503,ch);
 const rows=await env.DB.prepare(
   `SELECT * FROM comments WHERE ${ident(pc)}=? ORDER BY created_at ASC LIMIT 200`
 ).bind(pid).all<Row>();
 const comments=[];
 for(const r of rows.results||[]){
   const cid=rowId(r);
   const uid=String(r[uc]||'');
   const author=uid?await env.DB.prepare('SELECT id,username,role,status,created_at,updated_at FROM users WHERE id=? LIMIT 1').bind(uid).first<Row>():null;
   let like_count=0;
   let liked=false;
   try{
     const lc=await columns(env.DB,'comment_likes');
     const lpc=first(lc,['comment_id']),luc=first(lc,['user_id','actor_id']);
     if(lpc&&luc){
       const count=await env.DB.prepare(`SELECT COUNT(*) AS n FROM comment_likes WHERE ${ident(lpc)}=?`).bind(cid).first<{n:number}>();
       like_count=Number(count?.n||0);
       const mine=await env.DB.prepare(`SELECT 1 FROM comment_likes WHERE ${ident(lpc)}=? AND ${ident(luc)}=? LIMIT 1`).bind(cid,a.user.id).first();
       liked=Boolean(mine);
     }
   }catch{}
   comments.push({...r,id:cid,content:r[cc],author,like_count,liked});
 }
 return json({comments},200,ch);
}
if(path.startsWith('/posts/')&&path.endsWith('/comments')&&req.method==='POST'){requireAuth(a);const pid=requireId(decodeURIComponent(path.slice(7,-9)),'post id'),post=await env.DB.prepare('SELECT * FROM posts WHERE id=? LIMIT 1').bind(pid).first<Row>();if(!post)return json({error:'Post not found'},404,ch);const owner=rowId(post),b=await body(),content=text(b.content).trim().slice(0,2000),parent=text(b.parent_id)||undefined;if(!content)return json({error:'Comment is required'},400,ch);if(await blocked(env,a.user.id,owner))return json({error:'Forbidden'},403,ch);if(parent){const p=await env.DB.prepare('SELECT * FROM comments WHERE id=? LIMIT 1').bind(parent).first<Row>();if(!p||rowId(p)!==pid)return json({error:'Invalid parent comment'},400,ch);}const c=await columns(env.DB,'comments'),pc=first(c,['post_id']),uc=first(c,['user_id','author_id']),cc=first(c,['content','body']);if(!pc||!uc||!cc)return json({error:'Comments unavailable'},503,ch);const cid=newId();await insert(env.DB,'comments',{id:cid,comment_id:cid,post_id:pid,user_id:a.user.id,author_id:a.user.id,content,body:content,parent_id:parent,reply_to_id:parent,created_at:now(),updated_at:now()});if(owner!==a.user.id)await notify(env,owner,a.user.id,parent?'reply':'comment',cid);await mentionText(env,a.user.id,content,cid,'comment');return json({comment_id:cid},201,ch);}
const commentAct=path.match(/^\/comments\/([^/]+)\/(like|delete)$/);if(commentAct&&req.method==='POST'){requireAuth(a);const cid=requireId(decodeURIComponent(commentAct[1]),'comment id'),comment=await env.DB.prepare('SELECT * FROM comments WHERE id=? LIMIT 1').bind(cid).first<Row>();if(!comment)return json({error:'Comment not found'},404,ch);const author=rowId(comment);if(commentAct[2]==='delete'){if(author!==a.user.id&&!await isAdmin(env,a.user.id))return json({error:'Forbidden'},403,ch);await env.DB.prepare('DELETE FROM comments WHERE id=? OR comment_id=?').bind(cid,cid).run();return json({ok:true},200,ch);}if(await blocked(env,a.user.id,author))return json({error:'Forbidden'},403,ch);const c=await columns(env.DB,'comment_likes'),cc=first(c,['comment_id']),uc=first(c,['user_id','actor_id']);if(!cc||!uc)return json({error:'Comment likes unavailable'},503,ch);const ex=await env.DB.prepare(`SELECT 1 FROM comment_likes WHERE ${ident(cc)}=? AND ${ident(uc)}=? LIMIT 1`).bind(cid,a.user.id).first();if(ex){await env.DB.prepare(`DELETE FROM comment_likes WHERE ${ident(cc)}=? AND ${ident(uc)}=?`).bind(cid,a.user.id).run();return json({liked:false},200,ch);}await insert(env.DB,'comment_likes',{id:newId(),comment_id:cid,user_id:a.user.id,actor_id:a.user.id,created_at:now()});if(author!==a.user.id)await notify(env,author,a.user.id,'comment_like',cid);return json({liked:true},200,ch);}
if(path==='/follows'&&req.method==='POST'){requireAuth(a);const b=await body(),target=text(b.user_id);if(!target||target===a.user.id)return json({error:'Invalid follow target'},400,ch);if(await blocked(env,a.user.id,target)||await blocked(env,target,a.user.id))return json({error:'Unable to follow this user'},403,ch);const tcSettings=await settingRow(env,target),sc=tcSettings?await columns(env.DB,'user_settings'):new Set<string>();if(tcSettings&&sc.has('private_account')&&Boolean(tcSettings.private_account))return json({following:false,pending:true},202,ch);const c=await columns(env.DB,'follows'),fc=first(c,['follower_id','from_user_id','user_id']),tc=first(c,['following_id','to_user_id','target_user_id']);if(!fc||!tc)return json({error:'Follows unavailable'},503,ch);const ex=await env.DB.prepare(`SELECT 1 FROM follows WHERE ${ident(fc)}=? AND ${ident(tc)}=? LIMIT 1`).bind(a.user.id,target).first();if(ex){await env.DB.prepare(`DELETE FROM follows WHERE ${ident(fc)}=? AND ${ident(tc)}=?`).bind(a.user.id,target).run();return json({following:false},200,ch);}await insert(env.DB,'follows',{id:newId(),follower_id:a.user.id,from_user_id:a.user.id,user_id:a.user.id,following_id:target,to_user_id:target,target_user_id:target,created_at:now()});await notify(env,target,a.user.id,'follow',a.user.id);return json({following:true},200,ch);}
if(path==='/notifications'&&req.method==='GET'){requireAuth(a);const c=await columns(env.DB,'notifications'),uc=first(c,['user_id','recipient_id']);if(!uc)return json({notifications:[]},200,ch);const r=await env.DB.prepare(`SELECT n.*,u.username AS actor_username FROM notifications n LEFT JOIN users u ON u.id=n.actor_id WHERE n.${ident(uc)}=? ORDER BY n.created_at DESC LIMIT 50`).bind(a.user.id).all<Row>();return json({notifications:r.results||[]},200,ch);}
const nr=path.match(/^\/notifications\/([^/]+)\/read$/);if(nr&&req.method==='POST'){requireAuth(a);const nid=requireId(decodeURIComponent(nr[1]),'notification id'),c=await columns(env.DB,'notifications'),ic=first(c,['id','notification_id']),uc=first(c,['user_id','recipient_id']),rc=first(c,['read_at']),ri=first(c,['is_read','read']);if(!ic||!uc)return json({error:'Notifications unavailable'},503,ch);const vals:Record<string,unknown>={};if(rc)vals[rc]=now();if(ri)vals[ri]=1;await update(env.DB,'notifications',`${ident(ic)}=? AND ${ident(uc)}=?`,[nid,a.user.id],vals);return json({ok:true},200,ch);}
if(path==='/notifications/read-all'&&req.method==='POST'){requireAuth(a);const c=await columns(env.DB,'notifications'),uc=first(c,['user_id','recipient_id']),rc=first(c,['read_at']),ri=first(c,['is_read','read']);if(!uc)return json({error:'Notifications unavailable'},503,ch);const vals:Record<string,unknown>={};if(rc)vals[rc]=now();if(ri)vals[ri]=1;await update(env.DB,'notifications',`${ident(uc)}=?`,[a.user.id],vals);return json({ok:true},200,ch);}
if(path==='/search'&&req.method==='GET'){requireAuth(a);const q=text(url.searchParams.get('q')).trim(),limit=Math.min(Math.max(Number(url.searchParams.get('limit')||20),1),50);if(q.length<2)return json({users:[],posts:[]},200,ch);const us=await env.DB.prepare('SELECT id,username FROM users WHERE lower(username) LIKE lower(?) LIMIT ?').bind(`%${q}%`,limit).all<Row>(),ps=await env.DB.prepare('SELECT * FROM posts WHERE lower(caption) LIKE lower(?) ORDER BY created_at DESC LIMIT ?').bind(`%${q}%`,limit).all<Row>();return json({users:us.results||[],posts:ps.results||[]},200,ch);}
if(path==='/settings'&&req.method==='GET'){requireAuth(a);return json({settings:await settingRow(env,a.user.id)||{}},200,ch);}
if(path==='/settings'&&req.method==='PATCH'){requireAuth(a);const b=await body();try{await insert(env.DB,'user_settings',{id:newId(),user_id:a.user.id,created_at:now()});}catch{}const c=await columns(env.DB,'user_settings'),uc=first(c,['user_id','owner_id']);if(!uc)return json({error:'Settings unavailable'},503,ch);const allowed=['allow_messages','private_account','show_online_status','read_receipts','allow_mentions','notify_likes','notify_comments','notify_follows','notify_messages'];const values:Record<string,unknown>={updated_at:now()};for(const k of allowed)if(typeof b[k]==='boolean')values[k]=b[k];await update(env.DB,'user_settings',`${ident(uc)}=?`,[a.user.id],values);return json({ok:true},200,ch);}
for(const kind of ['blocks','mutes'] as const){if(path===`/${kind}`&&req.method==='POST'){requireAuth(a);const b=await body(),target=text(b.user_id);if(!target||target===a.user.id)return json({error:'Invalid target'},400,ch);const c=await columns(env.DB,kind),uc=first(c,['blocker_id','muter_id','user_id','from_user_id']),tc=first(c,['blocked_id','muted_id','target_user_id','to_user_id']);if(!uc||!tc)return json({error:'Unavailable'},503,ch);const ex=await env.DB.prepare(`SELECT 1 FROM ${ident(kind)} WHERE ${ident(uc)}=? AND ${ident(tc)}=? LIMIT 1`).bind(a.user.id,target).first();if(ex){await env.DB.prepare(`DELETE FROM ${ident(kind)} WHERE ${ident(uc)}=? AND ${ident(tc)}=?`).bind(a.user.id,target).run();return json({active:false},200,ch);}await insert(env.DB,kind,{id:newId(),blocker_id:a.user.id,muter_id:a.user.id,user_id:a.user.id,from_user_id:a.user.id,blocked_id:target,muted_id:target,target_user_id:target,to_user_id:target,created_at:now()});return json({active:true},201,ch);}}
if(path==='/messages/with'&&req.method==='GET'){requireAuth(a);const target=text(url.searchParams.get('user_id'));if(!target||target===a.user.id)return json({conversation_id:null},200,ch);if(await blocked(env,a.user.id,target)||await blocked(env,target,a.user.id))return json({conversation_id:null},200,ch);const pc=await columns(env.DB,'conversation_participants'),conv=first(pc,['conversation_id','conversation']),uc=first(pc,['user_id','participant_id']);if(!conv||!uc)return json({conversation_id:null},200,ch);const cid=text((await env.DB.prepare(`SELECT p1.${ident(conv)} AS cid FROM conversation_participants p1 JOIN conversation_participants p2 ON p1.${ident(conv)}=p2.${ident(conv)} WHERE p1.${ident(uc)}=? AND p2.${ident(uc)}=? LIMIT 1`).bind(a.user.id,target).first<Row>())?.cid);return json({conversation_id:cid||null},200,ch);}
if(path==='/messages'&&req.method==='POST'){requireAuth(a);const b=await body(),target=text(b.recipient_id||b.user_id),content=text(b.content).trim().slice(0,4000);if(!target||!content)return json({error:'Recipient and message are required'},400,ch);const recipient=await env.DB.prepare('SELECT id FROM users WHERE id=? LIMIT 1').bind(target).first<Row>();if(!recipient)return json({error:'Recipient not found'},404,ch);if(target===a.user.id)return json({error:'You cannot message yourself'},400,ch);if(await blocked(env,a.user.id,target)||!await canMessage(env,a.user.id,target))return json({error:'Messaging is not available for this recipient'},403,ch);const pc=await columns(env.DB,'conversation_participants'),conv=first(pc,['conversation_id']),uc=first(pc,['user_id','participant_id']);if(!conv||!uc)return json({error:'Messages unavailable'},503,ch);let cid=text((await env.DB.prepare(`SELECT p1.${ident(conv)} AS cid FROM conversation_participants p1 JOIN conversation_participants p2 ON p1.${ident(conv)}=p2.${ident(conv)} WHERE p1.${ident(uc)}=? AND p2.${ident(uc)}=? LIMIT 1`).bind(a.user.id,target).first<Row>())?.cid);if(!cid){cid=newId();await insert(env.DB,'conversations',{id:cid,conversation_id:cid,created_at:now(),updated_at:now()});await insert(env.DB,'conversation_participants',{id:newId(),conversation_id:cid,user_id:a.user.id,participant_id:a.user.id,created_at:now()});await insert(env.DB,'conversation_participants',{id:newId(),conversation_id:cid,user_id:target,participant_id:target,created_at:now()});}const mc=await columns(env.DB,'messages'),cc=first(mc,['conversation_id']),sc=first(mc,['sender_id','user_id','from_user_id']),bc=first(mc,['content','body','message']);if(!cc||!sc||!bc)return json({error:'Messages unavailable'},503,ch);const mid=newId();await insert(env.DB,'messages',{id:mid,message_id:mid,conversation_id:cid,sender_id:a.user.id,user_id:a.user.id,from_user_id:a.user.id,content,body:content,created_at:now(),read_at:null,is_read:0});await notify(env,target,a.user.id,'message',cid);return json({conversation_id:cid,message_id:mid},201,ch);}
const me=path.match(/^\/messages\/([^/]+)$/);if(me&&req.method==='PATCH'){requireAuth(a);const mid=requireId(decodeURIComponent(me[1]),'message id'),b=await body(),content=text(b.content).trim().slice(0,4000);if(!content)return json({error:'Message is required'},400,ch);const mc=await columns(env.DB,'messages'),ic=first(mc,['id','message_id']),sc=first(mc,['sender_id','user_id','from_user_id']),cc=first(mc,['content','body','message']);if(!ic||!sc||!cc)return json({error:'Messages unavailable'},503,ch);const row=await env.DB.prepare(`SELECT * FROM messages WHERE ${ident(ic)}=? LIMIT 1`).bind(mid).first<Row>();if(!row)return json({error:'Message not found'},404,ch);if(text(row[sc])!==a.user.id)return json({error:'Forbidden'},403,ch);await update(env.DB,'messages',`${ident(ic)}=?`,[mid],{[cc]:content,body:content,updated_at:now()});return json({ok:true},200,ch);}
if(path==='/messages'&&req.method==='GET'){requireAuth(a);const cid=text(url.searchParams.get('conversation_id'));if(!cid)return json({messages:[]},200,ch);const pc=await columns(env.DB,'conversation_participants'),conv=first(pc,['conversation_id','conversation']),uc=first(pc,['user_id','participant_id']);if(!conv||!uc)return json({messages:[]},200,ch);const convCol=conv as string,userCol=uc as string;const member=await env.DB.prepare(`SELECT 1 FROM conversation_participants WHERE ${ident(convCol)}=? AND ${ident(userCol)}=? LIMIT 1`).bind(cid,a.user.id).first();if(!member)return json({error:'Forbidden'},403,ch);const mc=await columns(env.DB,'messages'),cc=first(mc,['conversation_id']);if(!cc)return json({messages:[]},200,ch);const msgCol=cc as string,r=await env.DB.prepare(`SELECT m.*,u.username AS sender_username FROM messages m LEFT JOIN users u ON u.id=m.sender_id WHERE m.${ident(msgCol)}=? ORDER BY m.created_at ASC LIMIT 200`).bind(cid).all<Row>();return json({messages:r.results||[]},200,ch);}
const mr=path.match(/^\/messages\/([^/]+)\/read$/);if(mr&&req.method==='POST'){requireAuth(a);const cid=requireId(decodeURIComponent(mr[1]),'conversation id'),pc=await columns(env.DB,'conversation_participants'),conv=first(pc,['conversation_id','conversation']),uc=first(pc,['user_id','participant_id']);if(!conv||!uc)return json({error:'Messages unavailable'},503,ch);const convCol=conv as string,userCol=uc as string,member=await env.DB.prepare(`SELECT 1 FROM conversation_participants WHERE ${ident(convCol)}=? AND ${ident(userCol)}=? LIMIT 1`).bind(cid,a.user.id).first();if(!member)return json({error:'Forbidden'},403,ch);const mc=await columns(env.DB,'messages'),cc=first(mc,['conversation_id']),rc=first(mc,['read_at']),ri=first(mc,['is_read','read']);const vals:Record<string,unknown>={};if(rc)vals[rc]=now();if(ri)vals[ri]=1;if(!Object.keys(vals).length)return json({ok:true},200,ch);const sender=first(mc,['sender_id','user_id','from_user_id']);const where=[`${ident(cc as string)}=?`],args:unknown[]=[cid];if(sender){where.push(`${ident(sender as string)}!=?`);args.push(a.user.id);}await update(env.DB,'messages',where.join(' AND '),args,vals);return json({ok:true},200,ch);}
if(path==='/earn/offers'&&req.method==='GET'){requireAuth(a);const r=await env.DB.prepare("SELECT * FROM reward_offers WHERE status IS NULL OR lower(status) IN ('active','enabled','live') ORDER BY created_at DESC LIMIT 100").all<Row>().catch(()=>({results:[]}));return json({offers:r.results||[]},200,ch);}
const postback=path.match(/^\/rewards\/([^/]+)\/postback$/);if(postback&&req.method==='POST'){const provider=postback[1] as string;if(env.OFFERWALL_PROVIDER&&provider!==env.OFFERWALL_PROVIDER)return json({error:'Provider not enabled'},404,ch);const raw=await req.text();if(!await validatePostback(env,req,raw))return json({error:'Invalid reward signature'},401,ch);if(!await rateLimit(env,req,'reward_postback',120,60))return json({error:'Rate limited'},429,ch);let b:Record<string,unknown>;try{b=JSON.parse(raw);}catch{return json({error:'Invalid payload'},400,ch);}const eventId=text(b.event_id||b.transaction_id||b.reference_id),userId=text(b.user_id||b.external_user_id),amount=Number(b.amount),offerId=text(b.offer_id);if(!eventId||!userId||!Number.isFinite(amount))return json({error:'Invalid reward payload'},400,ch);const u=await getUser(env.DB,userId);if(!u)return json({error:'Invalid reward recipient'},404,ch);const result=await rewardCredit(env,userId,amount,provider,eventId,offerId);return json(result,result.ok?200:(result.status||409),ch);}
if(path==='/wallet'&&req.method==='GET'){requireAuth(a);return json(await walletInfo(env,a.user.id),200,ch);}
if(path==='/withdrawals'&&req.method==='POST'){requireAuth(a);const b=await body(),amount=Number(b.amount),provider=text(b.provider).toLowerCase(),destination=text(b.destination).trim();if(!Number.isInteger(amount)||amount<=0||amount>100000000||!destination)return json({error:'Invalid withdrawal request'},400,ch);if(!['paystack','paypal'].includes(provider))return json({error:'Unsupported withdrawal provider'},400,ch);if(provider==='paystack'&&!env.PAYSTACK_SECRET_KEY)return json({error:'Paystack is not active'},503,ch);if(provider==='paypal'&&(!env.PAYPAL_CLIENT_ID||!env.PAYPAL_CLIENT_SECRET))return json({error:'PayPal is not active'},503,ch);const c=await columns(env.DB,'wallets'),uc=first(c,['user_id','owner_id']),bc=await balanceColumn(env.DB);if(!uc||!bc.available)return json({error:'Wallet unavailable'},503,ch);const wallet=await env.DB.prepare(`SELECT * FROM wallets WHERE ${ident(uc)}=? LIMIT 1`).bind(a.user.id).first<Row>();if(!wallet)return json({error:'Wallet unavailable'},409,ch);const wid=text(wallet.id??wallet.wallet_id??a.user.id),current=Number(wallet[bc.available]??0);if(current<amount)return json({error:'Insufficient available balance'},409,ch);const stmts=[] as D1PreparedStatement[];if(bc.pending)stmts.push(env.DB.prepare(`UPDATE wallets SET ${ident(bc.available as string)}=?, ${ident(bc.pending as string)}=COALESCE(${ident(bc.pending as string)},0)+? WHERE ${ident(uc as string)}=?`).bind(current-amount,amount,a.user.id));else stmts.push(env.DB.prepare(`UPDATE wallets SET ${ident(bc.available as string)}=? WHERE ${ident(uc as string)}=?`).bind(current-amount,a.user.id));stmts.push(await insertStmt(env.DB,'withdrawals',{id:newId(),withdrawal_id:newId(),user_id:a.user.id,wallet_id:wid,provider,status:'reserved',state:'reserved',amount,destination,created_at:now(),updated_at:now()}));stmts.push(await insertStmt(env.DB,'wallet_transactions',{id:newId(),wallet_id:wid,user_id:a.user.id,type:'withdrawal_reservation',transaction_type:'withdrawal',direction:'debit',amount,balance_after:current-amount,status:'reserved',reference_id:destination,created_at:now()}));try{await env.DB.batch(stmts);return json({status:'reserved'},201,ch);}catch{return json({error:'Withdrawal could not be reserved'},409,ch);}}
if(path==='/admin/reports'&&req.method==='POST'){requireAuth(a);const b=await body(),target=text(b.target_id||b.post_id||b.user_id),reason=text(b.reason).trim().slice(0,1000);if(!target||!reason)return json({error:'Target and reason are required'},400,ch);await insert(env.DB,'reports',{id:newId(),reporter_id:a.user.id,user_id:b.user_id?target:undefined,target_id:target,post_id:b.post_id,user_id_reported:b.user_id,reason,status:'open',created_at:now()});return json({ok:true},201,ch);}
if(path==='/admin/reports'&&req.method==='GET'){requireAuth(a);if(!await isAdmin(env,a.user.id))return json({error:'Forbidden'},403,ch);const r=await env.DB.prepare('SELECT * FROM reports ORDER BY created_at DESC LIMIT 100').all<Row>();return json({reports:r.results||[]},200,ch);}
if(path==='/admin/moderate'&&req.method==='POST'){requireAuth(a);if(!await isAdmin(env,a.user.id))return json({error:'Forbidden'},403,ch);const b=await body(),target=text(b.target_id),action=text(b.action).trim().slice(0,100),reason=text(b.reason).trim().slice(0,1000);if(!target||!action)return json({error:'Target and action are required'},400,ch);await insert(env.DB,'moderation_actions',{id:newId(),admin_id:a.user.id,moderator_id:a.user.id,target_id:target,action,status:'applied',reason,created_at:now()});if(['ban','disable','suspend'].includes(action.toLowerCase())){const c=await columns(env.DB,'users'),ic=first(c,['id','user_id']),sc=first(c,['status','account_status']);if(ic&&sc)await update(env.DB,'users',`${ident(ic)}=?`,[target],{[sc]:action.toLowerCase(),updated_at:now()});}await securityEvent(env,'admin_moderation',a.user.id,req,{target,action});return json({ok:true},200,ch);}
if(path==='/music/search'&&req.method==='GET'){
requireAuth(a);
const q=text(url.searchParams.get('q')).trim();
if(q.length<2)return json({tracks:[]},200,ch);
const tracks:any[]=[];
try{
const u=new URL('https://itunes.apple.com/search');
u.searchParams.set('term',q);
u.searchParams.set('country','NG');
u.searchParams.set('media','music');
u.searchParams.set('entity','song');
u.searchParams.set('limit','10');
const r=await fetch(u.toString());
if(r.ok){
const d=await r.json() as any;
for(const x of (d.results||[]))tracks.push({provider:'itunes',id:String(x.trackId||''),title:x.trackName||'',artist:x.artistName||'',album:x.collectionName||'',artwork_url:x.artworkUrl100||'',duration_ms:x.trackTimeMillis||0,external_url:x.trackViewUrl||'',audio_url:x.previewUrl||'',source_url:x.trackViewUrl||''});
}
}catch{}
try{
const u=new URL('https://api.openverse.org/v1/audio/');
u.searchParams.set('q',q);
u.searchParams.set('page_size','10');
const r=await fetch(u.toString(),{headers:{accept:'application/json'}});
if(r.ok){
const d=await r.json() as any;
for(const x of (d.results||[]))tracks.push({provider:'openverse',id:String(x.id||x.identifier||''),title:x.title||'',artist:x.creator||'',album:'',artwork_url:x.thumbnail||'',duration_ms:Number(x.duration||0),external_url:x.foreign_landing_url||x.source_url||'',audio_url:x.url||'',source_url:x.foreign_landing_url||'',license:x.license||'',license_url:x.license_url||'',creator:x.creator||''});
}
}catch{}
return json({tracks:tracks.filter((x)=>x.title&&x.audio_url).slice(0,20)},200,ch);
}
return json({error:'Not found'},404,ch);}
export default {async fetch(req:Request,env:Env){try{return await handle(env,req);}catch(e){const status=Number((e as any)?.status)||500;return json({error:status===401?'Authentication required':status<500?text((e as any)?.message):'Internal server error'},status,cors(env,req));}}};
