import { API_BASE } from './api';
import { FormEvent, ReactNode, useEffect, useMemo, useState } from 'react';
import { api, ApiError, Message, Post, User } from './api';

type Section='home'|'search'|'create'|'earn'|'wallet'|'profile'|'settings'|'notifications'|'messages';
type MessageContext={conversationId:string;recipientId?:string;recipientUsername:string;recipientAvatar?:string|null};
const nav=[['home','Home','⌂'],['search','Search','⌕'],['create','Create','+'],['earn','Earn','◇'],['wallet','Wallet','◫'],['profile','Profile','○']] as const;
const base=()=>API_BASE;
const messageDate=(value:unknown)=>{const n=Number(value);return Number.isFinite(n)?new Date(n*1000).toLocaleString():''};
function contextFromUrl():MessageContext|null{const p=new URLSearchParams(window.location.search),conversationId=p.get('conversation_id')||'';if(!conversationId)return null;return {conversationId,recipientId:p.get('recipient_id')||undefined,recipientUsername:p.get('recipient_username')||'Sphere user',recipientAvatar:p.get('recipient_avatar')||null}}

export default function App(){const initialContext=contextFromUrl();const [section,setSection]=useState<Section>(initialContext?'messages':'home');const[user,setUser]=useState<User|null>(null);const[loading,setLoading]=useState(true);const[messageContext,setMessageContext]=useState<MessageContext|null>(initialContext);useEffect(()=>{api.session().then(r=>setUser(r.user)).catch(()=>setUser(null)).finally(()=>setLoading(false));},[]);if(loading)return <div className="app-shell"><div className="loading">Loading Sphere…</div></div>;if(!user)return <Auth onAuth={setUser}/>;const go=(s:Section)=>{if(s!=='messages'){const url=new URL(window.location.href);url.searchParams.delete('conversation_id');url.searchParams.delete('recipient_id');url.searchParams.delete('recipient_username');url.searchParams.delete('recipient_avatar');window.history.replaceState(null,'',url);setMessageContext(null)}setSection(s)};const openMessages=(context?:MessageContext)=>{setMessageContext(context||null);const url=new URL(window.location.href);if(context?.conversationId){url.searchParams.set('conversation_id',context.conversationId);if(context.recipientId)url.searchParams.set('recipient_id',context.recipientId);else url.searchParams.delete('recipient_id');url.searchParams.set('recipient_username',context.recipientUsername);if(context.recipientAvatar)url.searchParams.set('recipient_avatar',context.recipientAvatar);else url.searchParams.delete('recipient_avatar')}else{url.searchParams.delete('conversation_id');url.searchParams.delete('recipient_id');url.searchParams.delete('recipient_username');url.searchParams.delete('recipient_avatar')}window.history.replaceState(null,'',url);setSection('messages')};return <div className="app-shell"><header className="topbar"><button className="brand brand-button" onClick={()=>go('home')}>Sphere</button><div className="topbar-actions"><button aria-label="Notifications" onClick={()=>go('notifications')}>♡</button><button aria-label="Messages" onClick={()=>openMessages()}>✉</button></div></header><main className="content">{section==='home'&&<Home user={user}/>}{section==='search'&&<Search onOpenMessages={openMessages}/>} {section==='create'&&<Create onCreated={()=>go('home')}/>} {section==='earn'&&<Earn/>}{section==='wallet'&&<Wallet/>}{section==='profile'&&<Profile user={user} onLogout={()=>api.logout().finally(()=>setUser(null))} onUpdated={setUser} onSettings={()=>go('settings')}/>} {section==='settings'&&<Settings/>}{section==='notifications'&&<Notifications onOpenMessages={openMessages}/>} {section==='messages'&&<Messages user={user} context={messageContext}/>}</main><nav className="bottom-nav" aria-label="Primary navigation">{nav.map(([id,label,icon])=><button key={id} className={section===id?'active':''} onClick={()=>go(id)}><span className="nav-icon">{icon}</span><span>{label}</span></button>)}</nav></div>}
function Auth({onAuth}:{onAuth:(u:User)=>void}){const[mode,setMode]=useState<'login'|'signup'|'forgot'>('login');const[username,setUsername]=useState('');const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[error,setError]=useState('');const[busy,setBusy]=useState(false);async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{if(mode==='forgot'){await api.forgotPassword(email);setError('If that account exists, a reset email has been sent.');return}const r=mode==='login'?await api.login({email,password}):await api.signup({username,email,password});onAuth(r.user);}catch(e){setError(e instanceof ApiError?e.message:'Unable to connect to Sphere.')}finally{setBusy(false)}}return <div className="auth-shell"><div className="auth-card"><div className="brand">Sphere</div><p className="eyebrow">Social + rewards</p><h1>{mode==='login'?'Welcome back':mode==='signup'?'Create your account':'Reset your password'}</h1><p className="muted">Real accounts, posts, media and rewards are stored on the Sphere backend.</p><form onSubmit={submit}>{mode==='signup'&&<label>Username<input value={username} onChange={e=>setUsername(e.target.value)} autoComplete="username" required minLength={3}/></label>}<label>Email<input value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" required/></label>{mode!=='forgot'&&<label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete={mode==='login'?'current-password':'new-password'} required minLength={8}/></label>}{error&&<div className={mode==='forgot'?'notice':'error'}>{error}</div>}<button className="primary" disabled={busy}>{busy?'Working…':mode==='login'?'Log in':mode==='signup'?'Create account':'Send reset email'}</button></form><div className="auth-links">{mode==='login'&&<button className="text-button" onClick={()=>{setMode('forgot');setError('')}}>Forgot password?</button>}<button className="text-button" onClick={()=>{setMode(mode==='login'?'signup':'login');setError('')}}>{mode==='signup'?'Already have an account? Log in':'Need an account? Sign up'}</button></div></div></div>}
function Heading({eyebrow,title,children}:{eyebrow:string;title:string;children?:ReactNode}){return <div className="section-heading"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1></div>{children}</div>}
function Empty({title,text:copy}:{title:string;text?:string}){return <div className="empty-state"><div className="empty-mark">S</div><h2>{title}</h2>{copy&&<p>{copy}</p>}</div>}
function Home({user}:{user:User}){const[posts,setPosts]=useState<Post[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const load=()=>{setLoading(true);api.posts().then(r=>setPosts(r.posts)).catch(e=>setError(e instanceof Error?e.message:'Unable to load feed')).finally(()=>setLoading(false))};useEffect(load,[]);return <section><Heading eyebrow="Social" title="For you"><button className="quiet-button" onClick={load}>Refresh</button></Heading>{loading&&<Empty title="Loading feed"/>}{error&&<div className="error-block">{error}</div>}{!loading&&!error&&!posts.length&&<Empty title="Your feed starts here" text="There are no posts available yet. Create an image post or follow people to build your feed."/>}<div className="feed">{posts.map(p=><PostCard key={String(p.id||p.post_id)} post={p} currentUser={user} onDeleted={(id)=>setPosts(current=>current.filter(x=>String(x.id||x.post_id)!==id))}/>)}</div></section>}
function PostCard({post,currentUser,onDeleted}:{post:Post;currentUser:User;onDeleted?:(id:string)=>void}){
 const[liked,setLiked]=useState(Boolean(post.liked));
 const[saved,setSaved]=useState(Boolean(post.saved));
 const[busy,setBusy]=useState(false);
 const[deleting,setDeleting]=useState(false);
 const[comments,setComments]=useState<any[]|null>(null);
 const[commentText,setCommentText]=useState('');
 const[commentBusy,setCommentBusy]=useState(false);
 const media=post.media||{};
 const key=media.object_key||media.r2_key||media.storage_key||media.key;
 const image=key?`${base()}/media/${encodeURIComponent(String(key))}`:media.url||media.public_url;
 const songTitle=post.song_title||post.music?.title||post.music_metadata?.title;
 const songArtist=post.song_artist||post.music?.artist||post.music_metadata?.artist;
 const songUrl=post.song_url||post.music?.external_url||post.music_metadata?.external_url;

 async function loadComments(){
   try{
     const r=await api.comments(String(post.id||post.post_id));
     setComments(r.comments||[]);
   }catch{
     setComments([]);
   }
 }

 async function act(kind:'like'|'save'){
   if(busy)return;
   setBusy(true);
   try{
     const r=kind==='like'
       ?await api.like(String(post.id||post.post_id))
       :await api.save(String(post.id||post.post_id));
     kind==='like'?setLiked(Boolean(r.liked)):setSaved(Boolean(r.saved));
   }catch{}finally{setBusy(false)}
 }

 async function addComment(){
   const text=commentText.trim();
   if(!text||commentBusy)return;
   setCommentBusy(true);
   try{
     await api.comment(String(post.id||post.post_id),text);
     setCommentText('');
     await loadComments();
   }catch(e){
     alert(e instanceof Error?e.message:'Unable to comment');
   }finally{setCommentBusy(false)}
 }

 async function removePost(){
   if(deleting)return;
   if(!confirm('Delete this post?'))return;
   setDeleting(true);
   try{
     const id=String(post.id||post.post_id);
     await api.deletePost(id);
     onDeleted?.(id);
   }catch(e){
     alert(e instanceof Error?e.message:'Unable to delete post');
   }finally{setDeleting(false)}
 }

 return <article className="post-card">
   {image?<img className="post-image" src={image} alt={post.caption||'Sphere post'}/>:<div className="media-placeholder">Image unavailable</div>}
   <div className="post-body">
     <div className="post-author">
       <div className="avatar">{post.author?.username?.[0]?.toUpperCase()||'S'}</div>
       <div><strong>@{post.author?.username||'sphere_user'}</strong><div className="muted">{post.author?.bio||'Sphere creator'}</div></div>
     </div>
     {post.caption&&<p>{post.caption}</p>}
     {songTitle&&<div className="music-line">♫ {songUrl?<a href={songUrl} target="_blank" rel="noreferrer">{songTitle}{songArtist?` — ${songArtist}`:''}</a>:<span>{songTitle}{songArtist?` — ${songArtist}`:''}</span>}</div>}
     <div className="post-actions">
       <button onClick={()=>act('like')} aria-pressed={liked}>♡ {liked?'Liked':'Like'}</button>
       <button onClick={()=>act('save')} aria-pressed={saved}>⌑ {saved?'Saved':'Save'}</button>
       <button onClick={loadComments}>{comments===null?'Comments':'Hide comments'}</button>
       {post.author?.id===currentUser.id&&<button className="quiet-button" onClick={removePost} disabled={deleting}>{deleting?'Deleting…':'Delete'}</button>}
       <span className="muted">{post.like_count||0} likes</span>
     </div>
     {comments!==null&&<div className="comments">
       <div className="comment-form">
         <input value={commentText} onChange={e=>setCommentText(e.target.value)} placeholder="Write a comment…" maxLength={2000}/>
         <button onClick={addComment} disabled={commentBusy||!commentText.trim()}>{commentBusy?'Posting…':'Post'}</button>
       </div>
       {!comments.length?<div className="muted">No comments yet.</div>:comments.map((c:any)=><div className="comment" key={c.id||c.comment_id}>
         <strong>@{c.author?.username||'sphere_user'}</strong>
         <span>{c.content||c.body||''}</span>
         <button onClick={async()=>{
           try{
             const r=await api.commentLike(String(c.id||c.comment_id));
             setComments(xs=>(xs||[]).map(x=>(x.id||x.comment_id)===(c.id||c.comment_id)?{...x,liked:r.liked,like_count:Math.max(0,Number(x.like_count||0)+(r.liked?1:-1))}:x));
           }catch{}
         }}>{c.liked?'♥':'♡'} {c.like_count||0}</button>
       </div>)}
     </div>}
   </div>
 </article>
}
function Search({onOpenMessages}:{onOpenMessages:(context:MessageContext)=>void}){const[q,setQ]=useState('');const[users,setUsers]=useState<User[]>([]);const[posts,setPosts]=useState<Post[]>([]);const[busy,setBusy]=useState(false);async function run(){if(q.trim().length<2)return;setBusy(true);try{const r=await api.search(q);setUsers(r.users);setPosts(r.posts)}catch{}finally{setBusy(false)}}return <section><Heading eyebrow="Discover" title="Search"/><div className="search-row"><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&run()} placeholder="Search users or posts"/><button className="primary small" onClick={run} disabled={busy}>Search</button></div>{!users.length&&!posts.length?<Empty title={q?'No matches':'Find people and posts'} text="Search uses real Sphere data."/>:<div className="results">{users.map(u=><div className="result" key={u.id}><div className="avatar">{u.username[0]?.toUpperCase()}</div><div><strong>@{u.username}</strong><p className="muted">{u.bio||'Sphere user'}</p></div><button className="quiet-button" onClick={()=>onOpenMessages({conversationId:'',recipientId:u.id,recipientUsername:u.username,recipientAvatar:u.avatar_url})}>Message</button></div>)}{posts.map(p=><div className="result" key={p.id||p.post_id}><strong>{p.caption||'Image post'}</strong><p className="muted">@{p.author?.username||'creator'}</p></div>)}</div>}</section>}
function Create({onCreated}:{onCreated:()=>void}){const[file,setFile]=useState<File|null>(null);const[caption,setCaption]=useState('');const[music,setMusic]=useState('');const[selectedMusic,setSelectedMusic]=useState<Music|undefined>();const[musicResults,setMusicResults]=useState<Music[]>([]);const[musicBusy,setMusicBusy]=useState(false);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const preview=useMemo(()=>file?URL.createObjectURL(file):'', [file]);async function searchMusic(){const q=music.trim();if(q.length<2){setMusicResults([]);return}setMusicBusy(true);try{const r=await api.musicSearch(q);setMusicResults(r.tracks||[])}catch{setMusicResults([])}finally{setMusicBusy(false)}}async function submit(e:FormEvent){e.preventDefault();if(!file)return setError('Choose an image first.');setBusy(true);setError('');try{const uploaded=await api.uploadImage(file);const musicData=selectedMusic|| (music.trim()?{provider:'manual-metadata',title:music.trim()}:undefined);await api.createPost({caption,music:musicData,imageKey:uploaded.key});onCreated()}catch(e){setError(e instanceof Error?e.message:'Unable to create post')}finally{setBusy(false)}}return <section><Heading eyebrow="Publish" title="Create"/><form className="composer" onSubmit={submit}><label>Image<input type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={e=>setFile(e.target.files?.[0]||null)} required/></label>{preview&&<img className="preview" src={preview} alt="Selected preview"/>}<label>Caption<textarea value={caption} onChange={e=>setCaption(e.target.value)} maxLength={2200} placeholder="Say something…"/></label><label>Song (optional)<input value={music} onChange={e=>{setMusic(e.target.value);setSelectedMusic(undefined)}} onKeyDown={e=>e.key==='Enter'&&(e.preventDefault(),searchMusic())} placeholder="Song title / artist"/><button type="button" className="quiet-button" onClick={searchMusic} disabled={musicBusy}>{musicBusy?'Searching…':'Search music'}</button></label>{selectedMusic&&<div className="music-line">♫ {selectedMusic.title}{selectedMusic.artist?` — ${selectedMusic.artist}`:''}</div>}{musicResults.length>0&&<div className="results">{musicResults.map((m:Music)=><button type="button" className="result" key={m.id||`${m.title}-${m.artist}`} onClick={()=>{setMusic(m.title||'');setSelectedMusic(m);setMusicResults([])}}><strong>{m.title}</strong><span className="muted">{m.artist}{m.album?` · ${m.album}`:''}</span></button>)}</div>}{error&&<div className="error">{error}</div>}<button className="primary" disabled={busy}>{busy?'Publishing…':'Publish image'}</button><p className="muted">One image per post. Sphere stores metadata only; it does not download copyrighted music or accept video uploads.</p></form></section>}
function Earn(){const[offers,setOffers]=useState<unknown[]|null>(null);useEffect(()=>{api.earn().then(r=>setOffers(r.offers)).catch(()=>setOffers([]))},[]);return <section><Heading eyebrow="Rewards" title="Earn"/>{offers===null?<Empty title="Loading offers"/>:offers.length?<div className="results">{offers.map((o:any,i)=><div className="result" key={o.id||i}><strong>{o.title||o.name||'Reward offer'}</strong><span className="muted">Provider configured</span></div>)}</div>:<Empty title="No earning offers are available right now." text="Offerwall providers remain safely inactive until production configuration is supplied. Sphere will never fabricate offers or earnings."/>}</section>}
function Wallet(){const[data,setData]=useState<{wallet:Record<string,unknown>|null;transactions:unknown[]}|null>(null);useEffect(()=>{api.wallet().then(setData).catch(()=>setData({wallet:null,transactions:[]}))},[]);return <section><Heading eyebrow="Money" title="Wallet"/>{data?.wallet?<div className="wallet-summary"><h2>Wallet connected</h2><p className="muted">Balance and transactions are read from persisted server-side wallet state.</p></div>:<Empty title="No wallet balance is available" text="No payment provider is active and no balance is fabricated."/>}</section>}
function Profile({user,onLogout,onUpdated,onSettings}:{user:User;onLogout:()=>void;onUpdated:(u:User)=>void;onSettings:()=>void}){const[bio,setBio]=useState(user.bio||'');const[username,setUsername]=useState(user.username);const[busy,setBusy]=useState(false);async function save(){setBusy(true);try{const r=await api.updateProfile({bio,username});onUpdated(r.user)}catch(e){alert(e instanceof Error?e.message:'Unable to update profile')}finally{setBusy(false)}}return <section><Heading eyebrow="Account" title="Profile"><button className="quiet-button" onClick={onLogout}>Log out</button></Heading><div className="profile-head"><div className="avatar large">{user.username[0]?.toUpperCase()}</div><div><h2>@{user.username}</h2><p className="muted">{user.email}</p></div></div><div className="composer"><label>Username<input value={username} onChange={e=>setUsername(e.target.value)}/></label><label>Bio<textarea value={bio} onChange={e=>setBio(e.target.value)} maxLength={500}/></label><button className="primary" onClick={save} disabled={busy}>{busy?'Saving…':'Save profile'}</button><button className="quiet-button full" onClick={onSettings}>Settings & privacy</button></div></section>}
function Settings(){const[settings,setSettings]=useState<Record<string,unknown>>({});const[busy,setBusy]=useState(true);useEffect(()=>{api.settings().then(r=>setSettings(r.settings)).finally(()=>setBusy(false))},[]);async function toggle(key:string){const next=!Boolean(settings[key]);setSettings(s=>({...s,[key]:next}));try{await api.updateSettings({[key]:next})}catch{setSettings(s=>({...s,[key]:!next}))}}return <section><Heading eyebrow="Account" title="Settings"/>{busy?<Empty title="Loading settings"/>:<div className="settings-list"><label className="setting"><span><strong>Allow messages</strong><small>Let other users start conversations with you.</small></span><input type="checkbox" checked={Boolean(settings.allow_messages??true)} onChange={()=>toggle('allow_messages')}/></label><label className="setting"><span><strong>Private account</strong><small>Keep privacy state controlled by the server.</small></span><input type="checkbox" checked={Boolean(settings.private_account)} onChange={()=>toggle('private_account')}/></label></div>}</section>}
function Notifications({onOpenMessages}:{onOpenMessages:(context:MessageContext)=>void}){const[data,setData]=useState<unknown[]|null>(null);useEffect(()=>{api.notifications().then(r=>setData(r.notifications)).catch(()=>setData([]))},[]);function messageContext(n:any):MessageContext|null{const conversationId=String(n.entity_id||n.reference_id||'');if(!conversationId)return null;const actorId=String(n.actor_id||n.actor?.id||'')||undefined;const actorUsername=String(n.actor?.username||n.actor_username||n.username||'')||((String(n.message||'').match(/@([a-z0-9_.]{3,30})/i)||[])[1]||'Sphere user');return {conversationId,recipientId:actorId,recipientUsername:actorUsername,recipientAvatar:n.actor?.avatar_url||n.actor_avatar_url||null}}return <section><Heading eyebrow="Activity" title="Notifications"/>{data===null?<Empty title="Loading notifications"/>:!data.length?<Empty title="You're all caught up" text="New follows, likes, comments and messages will appear here."/>:<div className="results">{data.map((n:any,i)=>{const isMessage=String(n.type||'').toLowerCase()==='message';const context=isMessage?messageContext(n):null;return <button type="button" className="result" key={n.id||i} onClick={()=>{if(context){api.readNotification(String(n.id||'')).catch(()=>{});onOpenMessages(context)}}}><strong>{n.message||n.type||'Activity'}</strong><span className="muted">{n.created_at?messageDate(n.created_at):''}</span></button>})}</div>}</section>}
function Messages({user,context}:{user:User;context:MessageContext|null}){const[conversation,setConversation]=useState(context?.conversationId||'');const[recipient,setRecipient]=useState(context?.recipientId||'');const[recipientUsername,setRecipientUsername]=useState(context?.recipientUsername||'');const[recipientAvatar,setRecipientAvatar]=useState<string|null|undefined>(context?.recipientAvatar);const[messages,setMessages]=useState<Message[]>([]);const[loading,setLoading]=useState(Boolean(context?.conversationId));const[error,setError]=useState('');const[textValue,setText]=useState('');const[busy,setBusy]=useState(false);
 useEffect(()=>{const cid=context?.conversationId||'';setConversation(cid);setRecipient(context?.recipientId||'');setRecipientUsername(context?.recipientUsername||'');setRecipientAvatar(context?.recipientAvatar);setMessages([]);setError('');if(!cid){setLoading(false);return}let active=true;const load=async()=>{try{setLoading(true);const r=await api.messages(cid);if(!active)return;const loaded=r.messages||[];setMessages(loaded);const other=loaded.find(m=>String(m.sender_id||m.user_id||m.from_user_id||'')!==user.id);if(!context?.recipientId&&other)setRecipient(String(other.sender_id||other.user_id||other.from_user_id||''));await api.readMessages(cid).catch(()=>{});}catch(e){if(active)setError(e instanceof Error?e.message:'Unable to load conversation')}finally{if(active)setLoading(false)}};load();const timer=window.setInterval(load,4000);return()=>{active=false;window.clearInterval(timer)}},[context?.conversationId,context?.recipientId,context?.recipientUsername,context?.recipientAvatar,user.id]);
 async function send(){const content=textValue.trim();if(!recipient||!content||busy)return;setBusy(true);try{const r=await api.sendMessage(recipient,content);const cid=r.conversation_id||conversation;if(cid!==conversation){setConversation(cid);const url=new URL(window.location.href);url.searchParams.set('conversation_id',cid);window.history.replaceState(null,'',url)}setText('');const refreshed=await api.messages(cid);setMessages(refreshed.messages||[]);await api.readMessages(cid).catch(()=>{});}catch(e){alert(e instanceof Error?e.message:'Unable to send message')}finally{setBusy(false)}}
 const visibleName=recipientUsername||'Messages';
 return <section style={{minHeight:'70vh',display:'flex',flexDirection:'column',paddingBottom:90}}><div className="section-heading"><div><p className="eyebrow">Private</p><h1 style={{marginBottom:4}}>{recipientAvatar?<span className="avatar" style={{display:'inline-flex',verticalAlign:'middle',marginRight:8}}>{visibleName[0]?.toUpperCase()||'S'}</span>:null}@{visibleName.replace(/^@/,'')}</h1><span className="muted">{conversation?'Conversation':'Choose someone to message'}</span></div></div>{!conversation?<Empty title="Messages" text="Open a message notification or choose a person from Search to open a chat."/>:loading?<Empty title="Loading conversation"/>:error?<div className="error-block">{error}</div>:!messages.length?<div className="empty-state" style={{padding:'32px 0'}}><div className="empty-mark">S</div><h2>No messages yet</h2><p>Send a message to start this conversation.</p></div>:<div className="message-list" style={{flex:1,overflowY:'auto',display:'flex',flexDirection:'column',gap:10,padding:'16px 0'}}>{messages.map((m,i)=>{const senderId=String(m.sender_id||m.user_id||m.from_user_id||'');const own=senderId===user.id;const senderName=own?user.username:recipientUsername||'User';return <div className="message" key={m.id||m.message_id||i} style={{alignSelf:own?'flex-end':'flex-start',maxWidth:'82%'}}><strong>@{senderName.replace(/^@/,'')}</strong><span>{m.content||m.body||''}</span><small className="muted">{messageDate(m.created_at)}</small></div>})}</div>}<div className="composer" style={{position:'fixed',left:0,right:0,bottom:0,zIndex:10,margin:0,padding:'12px 16px',background:'var(--surface, #fff)',borderTop:'1px solid var(--border, #ddd)',boxShadow:'0 -4px 16px rgba(0,0,0,.08)'}}><textarea value={textValue} onChange={e=>setText(e.target.value)} maxLength={4000} placeholder="Write a message…" rows={2} disabled={!conversation||!recipient}/><button className="primary" onClick={send} disabled={busy||!conversation||!recipient||!textValue.trim()}>{busy?'Sending…':'Send'}</button></div></section>}
