import {useEffect,useMemo,useState} from 'react';
import {api,API_BASE} from './api';

type WalletData={wallet:Record<string,any>|null;transactions:Record<string,any>[]};
type Provider={id:string;name:string;isConfigured:boolean;offerwall?:boolean;rewarding?:boolean;apiConfigured?:boolean};
type WithdrawalMethod='paystack'|'paypal'|'stripe';
const money=(v:any,currency='NGN')=>new Intl.NumberFormat('en-NG',{style:'currency',currency,maximumFractionDigits:2}).format(Number(v||0));
const label=(v:any)=>String(v||'').replaceAll('_',' ').replace(/\b\w/g,m=>m.toUpperCase());

export function EarnWallet(){
 const [wallet,setWallet]=useState<WalletData|null>(null),[providers,setProviders]=useState<Provider[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[withdrawAmount,setWithdrawAmount]=useState(''),[destination,setDestination]=useState(''),[method,setMethod]=useState<WithdrawalMethod>('paystack'),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[offerwall,setOfferwall]=useState('');
 const load=async()=>{setError('');try{const w=await api.wallet();setWallet(w);try{const r=await fetch(`${API_BASE}/api/earn/providers`,{credentials:'include'});const d=await r.json();setProviders(d.providers||[]);}catch{setProviders([]);}}catch(e){setError(e instanceof Error?e.message:'Unable to load wallet');}finally{setLoading(false);}};
 useEffect(()=>{load();},[]);
 const balance=useMemo(()=>Number(wallet?.wallet?.available_balance??wallet?.wallet?.balance_available??wallet?.wallet?.balance??0),[wallet]);
 const pending=Number(wallet?.wallet?.pending_balance??wallet?.wallet?.balance_pending??0);
 const cpalead=providers.find(p=>p.id==='cpalead');
 const cpagrip=providers.find(p=>p.id==='cpagrip');
 const openWall=async(type:'cpalead'|'cpagrip')=>{const p=type==='cpalead'?cpalead:cpagrip;if(!p?.isConfigured){setOfferwall(type==='cpalead'?'CPAlead is temporarily unavailable.':'CPAGrip is temporarily unavailable.');return;}setOfferwall('');const popup=window.open('about:blank','_blank');try{const r=await fetch(`${API_BASE}/api/earn/${type}/offerwall`,{credentials:'include'});const d=await r.json();if(!r.ok)throw new Error(d.error||'Offerwall is unavailable');if(!d.data?.url)throw new Error('Offerwall URL was not returned');if(popup&&!popup.closed)popup.location.href=d.data.url;else window.location.href=d.data.url;}catch(e){if(popup&&!popup.closed)popup.close();setOfferwall(e instanceof Error?e.message:'Offerwall is unavailable.');}};
 const withdraw=async()=>{const n=Number(withdrawAmount);if(!Number.isInteger(n)||n<=0){setNotice('Enter a valid whole-number amount.');return;}if(n>balance){setNotice('Amount exceeds your available balance.');return;}if(!destination.trim()){setNotice(`Enter your ${method==='paystack'?'Paystack recipient code':method==='paypal'?'PayPal email':'Stripe payout details'}.`);return;}if(method!=='paystack'){setNotice(`${method==='paypal'?'PayPal':'Stripe'} withdrawals are coming soon.`);return;}setBusy(true);setNotice('');try{await api.withdraw({amount:n,provider:'paystack',destination:destination.trim()});setWithdrawAmount('');setDestination('');setNotice('Withdrawal submitted.');await load();}catch(e){setNotice(e instanceof Error?e.message:'Withdrawal could not be submitted.');}finally{setBusy(false);}};
 if(loading)return <section className="earn-page"><div className="skeleton"/></section>;
 return <section className="earn-page">
  <header className="earn-hero"><div><span className="earn-kicker">Rewards</span><h1>Earn more with Sphere</h1><p>Complete offers, build your balance, and cash out when you're ready.</p></div></header>
  {error&&<div className="earn-alert">{error}</div>}
  <section className="wallet-card"><div><small>Available balance</small><strong>{money(balance)}</strong></div><div className="wallet-mini"><span>Pending</span><b>{money(pending)}</b></div></section>
  <section className="earn-panel earn-opportunities"><div className="panel-head"><div><small>Earn</small><h2>Choose an opportunity</h2></div></div><p className="earn-note">Pick an offerwall below. Your eligible rewards are tracked automatically.</p><div className="provider-list">
   <button className="provider-card" disabled={!cpalead?.isConfigured} onClick={()=>openWall('cpalead')}><span className="provider-icon">C</span><span className="provider-copy"><b>CPAlead</b><small>Offers & surveys · {cpalead?.isConfigured?'Available now':'Temporarily unavailable'}</small></span><span className="provider-arrow">›</span></button>
   <button className="provider-card" disabled={!cpagrip?.isConfigured} onClick={()=>openWall('cpagrip')}><span className="provider-icon">G</span><span className="provider-copy"><b>CPAGrip</b><small>Offers & rewards · {cpagrip?.isConfigured?'Available now':'Temporarily unavailable'}</small></span><span className="provider-arrow">›</span></button>
  </div>{offerwall&&<p className="earn-note">{offerwall}</p>}</section>
  <section className="earn-panel"><div className="panel-head"><div><small>Wallet</small><h2>Withdraw earnings</h2></div></div><div className="withdraw-methods" role="group" aria-label="Withdrawal method">
   {(['paystack','paypal','stripe'] as WithdrawalMethod[]).map(m=><button key={m} className={method===m?'method active':'method'} onClick={()=>{setMethod(m);setNotice('');setDestination('');}}><span className={`method-mark ${m}`}>{m==='paystack'?'P':m==='paypal'?'P':'S'}</span><span>{m==='paystack'?'Paystack':m==='paypal'?'PayPal':'Stripe'}</span>{m!=='paystack'&&<em>Soon</em>}</button>)}
  </div><div className="withdraw-grid"><input inputMode="numeric" value={withdrawAmount} onChange={e=>setWithdrawAmount(e.target.value)} placeholder="Amount in NGN"/><input value={destination} onChange={e=>setDestination(e.target.value)} placeholder={method==='paystack'?'Paystack recipient code':method==='paypal'?'PayPal email':'Stripe payout details'}/><button className="primary" disabled={busy} onClick={withdraw}>{busy?'Submitting…':method==='paystack'?'Withdraw':'Continue'}</button></div>{notice&&<p className="earn-note">{notice}</p>}</section>
  <section className="earn-panel"><div className="panel-head"><div><small>Activity</small><h2>Recent history</h2></div></div><div className="history-scroll">{wallet?.transactions?.length?wallet.transactions.map((t,i)=><div className="history-row" key={String(t.id??t.transaction_id??i)}><span><b>{label(t.type??t.transaction_type??t.status)}</b><small>{t.created_at?new Date(Number(t.created_at)*1000).toLocaleString():label(t.state??t.status)}</small></span><strong className={String(t.direction||'credit').toLowerCase()==='debit'?'debit':''}>{String(t.direction||'credit').toLowerCase()==='debit'?'-':'+'}{money(t.amount)}</strong></div>):<div className="empty compact"><h2>No activity yet</h2><p>Your completed rewards and withdrawals will appear here.</p></div>}</div></section>
 </section>;
}
