import {useState} from 'react';
import {A} from './SocialShared';
import {User} from './api';
import {Home} from './SocialHome';
import {Explore,Create} from './ExploreCreate';
import {ProfilePage,Settings} from './ProfileSettings';
import {Activity,Messages} from './ActivityMessages';
import {EarnWallet} from './EarnWallet';
import './sphere-finish.css';
import './sphere-v2.css';

type Page='home'|'explore'|'create'|'profile'|'settings'|'activity'|'messages'|'earn';

function SideNav({page,go,user}:{page:Page;go:(p:Page)=>void;user:User}){
 const items:[Page,string,string][]=[['home','Home','⌂'],['explore','Explore','⌕'],['create','Create','＋'],['earn','Earn','◈'],['messages','Messages','✉'],['activity','♡','♡']];
 return <aside className="sf-side sf-left"><button className="sf-side-brand" onClick={()=>go('home')}><b>S</b><span>Sphere</span></button><div className="sf-side-nav">{items.map(([id,label,icon])=><button key={id} className={page===id?'active':''} onClick={()=>go(id)}><i>{icon}</i><span>{id==='activity'?'Activity':label}</span>{id==='earn'&&<em>Rewards</em>}</button>)}<button className={page==='profile'?'active':''} onClick={()=>go('profile')}><i>◎</i><span>Profile</span></button><button className={page==='settings'?'active':''} onClick={()=>go('settings')}><i>⚙</i><span>Settings</span></button></div><button className="sf-side-create" onClick={()=>go('create')}>＋ <span>Create a post</span></button><button className="sf-side-profile" onClick={()=>go('profile')}><A u={user} s="s"/><span><b>{user.displayName||`@${user.username}`}</b><small>@{user.username}</small></span><i>›</i></button></aside>
}

function RightRail({go}:{go:(p:Page)=>void}){return <aside className="sf-side sf-right"><div className="rail-search" onClick={()=>go('explore')}>⌕ <span>Search Sphere</span></div><section className="rail-card"><div className="rail-head"><b>Who to follow</b><button onClick={()=>go('explore')}>See all</button></div><div className="rail-person"><span className="rail-avatar">T</span><span><b>TechVibes</b><small>@techvibes</small></span><button onClick={()=>go('explore')}>Follow</button></div><div className="rail-person"><span className="rail-avatar">M</span><span><b>MindsetDaily</b><small>@mindsetdaily</small></span><button onClick={()=>go('explore')}>Follow</button></div><div className="rail-person"><span className="rail-avatar">T</span><span><b>TravelMore</b><small>@travelmore</small></span><button onClick={()=>go('explore')}>Follow</button></div></section><section className="rail-card"><div className="rail-head"><b>Trending</b><button onClick={()=>go('explore')}>See all</button></div>{[['#GoodVibes','42.8K posts'],['#SelfGrowth','36.2K posts'],['#Tech','28.1K posts'],['#Lifestyle','21.4K posts']].map(([tag,count])=><button className="trend-row" key={tag} onClick={()=>go('explore')}><span><b>{tag}</b><small>{count}</small></span><i>›</i></button>)}</section><p className="rail-footer">Sphere · About · Help · Privacy · Terms</p></aside>}

export default function SphereFinish({user,onLogout}:{user:User;onLogout:()=>void}){const[p,setP]=useState<Page>('home'),[target,setTarget]=useState<User|null>(null),[cid,setCid]=useState(''),[currentUser,setCurrentUser]=useState(user);const open=(u:User,c='')=>{setTarget(u);setCid(c);setP('messages')};const go=(page:Page)=>{setP(page);if(page==='home'||page==='create'||page==='explore'||page==='earn'||page==='activity')setTarget(null)};return <div className="sf sf-product"><header><button className="header-profile" aria-label="Open your profile" onClick={()=>go('profile')}><A u={currentUser} s="s"/></button><button className="logo" aria-label="Go home" onClick={()=>go('home')}><b>S</b><span>Sphere</span></button><div className="head-actions"><button aria-label="Explore" onClick={()=>go('explore')}>⌕</button><button aria-label="Activity" onClick={()=>go('activity')}>♡</button><button aria-label="Messages" onClick={()=>go('messages')}>✉</button></div></header><div className={p==='home'?'sf-layout home-layout':'sf-layout'}><SideNav page={p} go={go} user={currentUser}/><main>{p==='home'&&<Home user={currentUser} profile={u=>{setTarget(u);setP('profile')}} message={open} create={()=>go('create')}/>} {p==='explore'&&<Explore user={currentUser} profile={u=>{setTarget(u);setP('profile')}} message={open}/>} {p==='create'&&<Create done={()=>go('home')}/>} {p==='profile'&&<ProfilePage user={target||currentUser} me={currentUser} back={()=>go('home')} message={open} settings={()=>go('settings')} logout={onLogout} onUpdated={u=>{if(u.id===currentUser.id){setCurrentUser(u);setTarget(u)}}}/>} {p==='settings'&&<Settings back={()=>go('profile')}/>} {p==='activity'&&<Activity message={open}/>} {p==='messages'&&<Messages me={currentUser} target={target} cid={cid} open={open}/>} {p==='earn'&&<EarnWallet/>}</main><RightRail go={go}/></div><nav>{[['home','⌂'],['explore','⌕'],['create','＋'],['earn','◈'],['messages','✉']].map(([x,i])=><button className={p===x?'on':''} key={x} aria-current={p===x?'page':undefined} aria-label={x==='home'?'Home':x==='explore'?'Explore':x==='create'?'Create':x==='earn'?'Earn':'Messages'} onClick={()=>go(x as Page)}><i>{i}</i><span>{x==='home'?'Home':x==='explore'?'Explore':x==='create'?'Create':x==='earn'?'Earn':'Messages'}</span></button>)}</nav></div>}
