import {useState} from 'react';
import {A} from './SocialShared';
import {User} from './api';
import {Home} from './SocialHome';
import {Explore,Create} from './ExploreCreate';
import {ProfilePage,Settings} from './ProfileSettings';
import {Activity,Messages} from './ActivityMessages';
import {EarnWallet} from './EarnWallet';
import './sphere-finish.css';
import './sphere-v2.css';

type Page='home'|'explore'|'create'|'profile'|'settings'|'activity'|'messages'|'earn';

function SideNav({page,go}:{page:Page;go:(p:Page)=>void}){
 const items:[Page,string,string][]=[['home','Home','⌂'],['explore','Explore','⌕'],['create','Create','＋'],['earn','Earn','◈'],['messages','Messages','✉'],['activity','Activity','♡']];
 return <aside className="sf-side sf-left"><div className="sf-side-brand"><b>S</b><span>Sphere</span></div><div className="sf-side-nav">{items.map(([id,label,icon])=><button key={id} className={page===id?'active':''} onClick={()=>go(id)}><i>{icon}</i><span>{label}</span></button>)}</div><button className="sf-side-profile" onClick={()=>go('profile')}><span className="sf-side-avatar"><span>•</span></span><span><b>Profile</b><small>View your profile</small></span></button></aside>
}

function RightRail(){return <aside className="sf-side sf-right"><section className="rail-card"><div className="rail-head"><b>Who to follow</b><button>See all</button></div><div className="rail-person"><span className="rail-avatar">T</span><span><b>TechVibes</b><small>@techvibes</small></span><button>Follow</button></div><div className="rail-person"><span className="rail-avatar">M</span><span><b>MindsetDaily</b><small>@mindsetdaily</small></span><button>Follow</button></div><div className="rail-person"><span className="rail-avatar">T</span><span><b>TravelMore</b><small>@travelmore</small></span><button>Follow</button></div></section><section className="rail-card"><div className="rail-head"><b>Trending</b><button>See all</button></div>{[['#GoodVibes','42.8K posts'],['#SelfGrowth','36.2K posts'],['#Tech','28.1K posts'],['#Lifestyle','21.4K posts']].map(([tag,count])=><button className="trend-row" key={tag}><span><b>{tag}</b><small>{count}</small></span><i>›</i></button>)}</section><p className="rail-footer">Sphere · About · Help · Privacy · Terms</p></aside>}

export default function SphereFinish({user,onLogout}:{user:User;onLogout:()=>void}){const[p,setP]=useState<Page>('home'),[target,setTarget]=useState<User|null>(null),[cid,setCid]=useState('');const open=(u:User,c='')=>{setTarget(u);setCid(c);setP('messages')};const go=(page:Page)=>{setP(page);if(page==='home'||page==='create'||page==='explore'||page==='earn'||page==='activity')setTarget(null)};return <div className="sf"><header><button className="header-profile" aria-label="Open your profile" onClick={()=>go('profile')}><A u={user} s="s"/></button><button className="logo" aria-label="Go home" onClick={()=>go('home')}><b>S</b><span>Sphere</span></button><div className="head-actions"><button aria-label="Explore" onClick={()=>go('explore')}>⌕</button><button aria-label="Activity" onClick={()=>go('activity')}>♡</button><button aria-label="Messages" onClick={()=>go('messages')}>✉</button></div></header><div className={p==='home'?'sf-layout home-layout':'sf-layout'}>{p==='home'&&<SideNav page={p} go={go}/>}<main>{p==='home'&&<Home user={user} profile={u=>{setTarget(u);setP('profile')}} message={open} create={()=>go('create')}/>} {p==='explore'&&<Explore user={user} profile={u=>{setTarget(u);setP('profile')}} message={open}/>} {p==='create'&&<Create done={()=>go('home')}/>} {p==='profile'&&<ProfilePage user={target||user} me={user} back={()=>go('home')} message={open} settings={()=>go('settings')} logout={onLogout}/>} {p==='settings'&&<Settings back={()=>go('profile')}/>} {p==='activity'&&<Activity message={open}/>} {p==='messages'&&<Messages me={user} target={target} cid={cid} open={open}/>} {p==='earn'&&<EarnWallet/>}</main>{p==='home'&&<RightRail/>}</div><nav>{[['home','⌂'],['explore','⌕'],['create','＋'],['earn','◈'],['messages','✉']].map(([x,i])=><button className={p===x?'on':''} key={x} aria-current={p===x?'page':undefined} aria-label={x==='home'?'Home':x==='explore'?'Explore':x==='create'?'Create':x==='earn'?'Earn':'Messages'} onClick={()=>go(x as Page)}><i>{i}</i><span>{x==='home'?'Home':x==='explore'?'Explore':x==='create'?'Create':x==='earn'?'Earn':'Messages'}</span></button>)}</nav></div>}
